/* SDRC Ideas header file */
#ifndef VDMSDRC_DEF
#define VDMSDRC_DEF

#define SDRC_NUMELEMTYPES 196

typedef struct {
    Vint shape, maxi, maxj, maxk;
    Vint featyp, featwo, iredir, esysid;
} fetypes;

/* TODO: the new elements 201+ */
static const fetypes sdrctypes[SDRC_NUMELEMTYPES] = {{SYS_SHAPEPOINT, 0, 0, 0, /* 1 */
                                                      SYS_ELEM_RIGID, 0, 0, 0},
                                                     {SYS_SHAPEPOINT, 0, 0, 0, SYS_ELEM_UNDEFINED, 0, 0, 0},
                                                     {SYS_SHAPEPOINT, 0, 0, 0, SYS_ELEM_UNDEFINED, 0, 0, 0},
                                                     {SYS_SHAPEPOINT, 0, 0, 0, SYS_ELEM_UNDEFINED, 0, 0, 0},
                                                     {SYS_SHAPEPOINT, 0, 0, 0, SYS_ELEM_UNDEFINED, 0, 0, 0},
                                                     {SYS_SHAPEPOINT, 0, 0, 0, SYS_ELEM_UNDEFINED, 0, 0, 0},
                                                     {SYS_SHAPEPOINT, 0, 0, 0, SYS_ELEM_UNDEFINED, 0, 0, 0},
                                                     {SYS_SHAPEPOINT, 0, 0, 0, SYS_ELEM_UNDEFINED, 0, 0, 0},
                                                     {SYS_SHAPEPOINT, 0, 0, 0, SYS_ELEM_UNDEFINED, 0, 0, 0},
                                                     {SYS_SHAPEPOINT, 0, 0, 0, SYS_ELEM_UNDEFINED, 0, 0, 0},
                                                     {SYS_SHAPELINE, 0, 0, 0, /* 11 */
                                                      SYS_ELEM_TRUSS, 0, 0, 0},
                                                     {SYS_SHAPEPOINT, 0, 0, 0, SYS_ELEM_UNDEFINED, 0, 0, 0},
                                                     {SYS_SHAPEPOINT, 0, 0, 0, SYS_ELEM_UNDEFINED, 0, 0, 0},
                                                     {SYS_SHAPEPOINT, 0, 0, 0, SYS_ELEM_UNDEFINED, 0, 0, 0},
                                                     {SYS_SHAPEPOINT, 0, 0, 0, SYS_ELEM_UNDEFINED, 0, 0, 0},
                                                     {SYS_SHAPEPOINT, 0, 0, 0, SYS_ELEM_UNDEFINED, 0, 0, 0},
                                                     {SYS_SHAPEPOINT, 0, 0, 0, SYS_ELEM_UNDEFINED, 0, 0, 0},
                                                     {SYS_SHAPEPOINT, 0, 0, 0, SYS_ELEM_UNDEFINED, 0, 0, 0},
                                                     {SYS_SHAPEPOINT, 0, 0, 0, SYS_ELEM_UNDEFINED, 0, 0, 0},
                                                     {SYS_SHAPEPOINT, 0, 0, 0, SYS_ELEM_UNDEFINED, 0, 0, 0},
                                                     {SYS_SHAPELINE, 0, 0, 0, /* 21 */
                                                      SYS_ELEM_BEAM, 0, 0, 0},
                                                     {SYS_SHAPELINE, 0, 0, 0, SYS_ELEM_BEAM, 0, 0, 0},
                                                     {SYS_SHAPELINE, 0, 0, 0, SYS_ELEM_BEAM, 0, 0, 0},
                                                     {SYS_SHAPELINE, 3, 0, 0, SYS_ELEM_BEAM, 0, 0, 0},
                                                     {SYS_SHAPELINE, 4, 0, 0, /* proposed  cubic beam */
                                                      SYS_ELEM_BEAM, 0, 0, 0},
                                                     {SYS_SHAPEPOINT, 0, 0, 0, SYS_ELEM_UNDEFINED, 0, 0, 0},
                                                     {SYS_SHAPEPOINT, 0, 0, 0, SYS_ELEM_UNDEFINED, 0, 0, 0},
                                                     {SYS_SHAPEPOINT, 0, 0, 0, SYS_ELEM_UNDEFINED, 0, 0, 0},
                                                     {SYS_SHAPEPOINT, 0, 0, 0, SYS_ELEM_UNDEFINED, 0, 0, 0},
                                                     {SYS_SHAPEPOINT, 0, 0, 0, SYS_ELEM_UNDEFINED, 0, 0, 0},
                                                     {SYS_SHAPELINE, 0, 0, 0, /* 31 */
                                                      SYS_ELEM_BEAM, 0, 0, 0},
                                                     {SYS_SHAPELINE, 0, 0, 0, SYS_ELEM_BEAM, 0, 0, 0},
                                                     {SYS_SHAPEPOINT, 0, 0, 0, SYS_ELEM_UNDEFINED, 0, 0, 0},
                                                     {SYS_SHAPEPOINT, 0, 0, 0, SYS_ELEM_UNDEFINED, 0, 0, 0},
                                                     {SYS_SHAPEPOINT, 0, 0, 0, SYS_ELEM_UNDEFINED, 0, 0, 0},
                                                     {SYS_SHAPEPOINT, 0, 0, 0, SYS_ELEM_UNDEFINED, 0, 0, 0},
                                                     {SYS_SHAPEPOINT, 0, 0, 0, SYS_ELEM_UNDEFINED, 0, 0, 0},
                                                     {SYS_SHAPEPOINT, 0, 0, 0, SYS_ELEM_UNDEFINED, 0, 0, 0},
                                                     {SYS_SHAPEPOINT, 0, 0, 0, SYS_ELEM_UNDEFINED, 0, 0, 0},
                                                     {SYS_SHAPEPOINT, 0, 0, 0, SYS_ELEM_UNDEFINED, 0, 0, 0},
                                                     {SYS_SHAPETRI, 0, 0, 0, /* 41 */
                                                      SYS_ELEM_SOLID, SYS_PLANESTRESS, 0, 0},
                                                     {SYS_SHAPETRI, 3, 0, 0, SYS_ELEM_SOLID, SYS_PLANESTRESS, 1, 0},
                                                     {SYS_SHAPETRI, 4, 0, 0, SYS_ELEM_SOLID, SYS_PLANESTRESS, 2, 0},
                                                     {SYS_SHAPEQUAD, 0, 0, 0, SYS_ELEM_SOLID, SYS_PLANESTRESS, 0, 0},
                                                     {SYS_SHAPEQUAD, 3, 0, 0, SYS_ELEM_SOLID, SYS_PLANESTRESS, 1, 0},
                                                     {SYS_SHAPEQUAD, 4, 0, 0, SYS_ELEM_SOLID, SYS_PLANESTRESS, 2, 0},
                                                     {SYS_SHAPEPOINT, 0, 0, 0, SYS_ELEM_UNDEFINED, 0, 0, 0},
                                                     {SYS_SHAPEPOINT, 0, 0, 0, SYS_ELEM_UNDEFINED, 0, 0, 0},
                                                     {SYS_SHAPEPOINT, 0, 0, 0, SYS_ELEM_UNDEFINED, 0, 0, 0},
                                                     {SYS_SHAPEPOINT, 0, 0, 0, SYS_ELEM_UNDEFINED, 0, 0, 0},
                                                     {SYS_SHAPETRI, 0, 0, 0, /* 51 */
                                                      SYS_ELEM_SOLID, SYS_PLANESTRAIN, 0, 0},
                                                     {SYS_SHAPETRI, 3, 0, 0, SYS_ELEM_SOLID, SYS_PLANESTRAIN, 1, 0},
                                                     {SYS_SHAPETRI, 4, 0, 0, SYS_ELEM_SOLID, SYS_PLANESTRAIN, 2, 0},
                                                     {SYS_SHAPEQUAD, 0, 0, 0, SYS_ELEM_SOLID, SYS_PLANESTRAIN, 0, 0},
                                                     {SYS_SHAPEQUAD, 3, 0, 0, SYS_ELEM_SOLID, SYS_PLANESTRAIN, 1, 0},
                                                     {SYS_SHAPEQUAD, 4, 0, 0, SYS_ELEM_SOLID, SYS_PLANESTRAIN, 2, 0},
                                                     {SYS_SHAPEPOINT, 0, 0, 0, SYS_ELEM_UNDEFINED, 0, 0, 0},
                                                     {SYS_SHAPEPOINT, 0, 0, 0, SYS_ELEM_UNDEFINED, 0, 0, 0},
                                                     {SYS_SHAPEPOINT, 0, 0, 0, SYS_ELEM_UNDEFINED, 0, 0, 0},
                                                     {SYS_SHAPEPOINT, 0, 0, 0, SYS_ELEM_UNDEFINED, 0, 0, 0},
                                                     {SYS_SHAPETRI, 0, 0, 0, /* 61 */
                                                      SYS_ELEM_SHELL, 0, 0, SYS_ELEMSYS_FIRSTEDGE},
                                                     {SYS_SHAPETRI, 3, 0, 0, SYS_ELEM_SHELL, 0, 1, SYS_ELEMSYS_FIRSTEDGE},
                                                     {SYS_SHAPETRI, 4, 0, 0, SYS_ELEM_SHELL, 0, 2, SYS_ELEMSYS_FIRSTEDGE},
                                                     {SYS_SHAPEQUAD, 0, 0, 0, SYS_ELEM_SHELL, 0, 0, SYS_ELEMSYS_STANDARD},
                                                     {SYS_SHAPEQUAD, 3, 0, 0, SYS_ELEM_SHELL, 0, 1, SYS_ELEMSYS_STANDARD},
                                                     {SYS_SHAPEQUAD, 4, 0, 0, SYS_ELEM_SHELL, 0, 2, SYS_ELEMSYS_STANDARD},
                                                     {SYS_SHAPEPOINT, 0, 0, 0, SYS_ELEM_UNDEFINED, 0, 0, 0},
                                                     {SYS_SHAPEPOINT, 0, 0, 0, SYS_ELEM_UNDEFINED, 0, 0, 0},
                                                     {SYS_SHAPEPOINT, 0, 0, 0, SYS_ELEM_UNDEFINED, 0, 0, 0},
                                                     {SYS_SHAPEPOINT, 0, 0, 0, SYS_ELEM_UNDEFINED, 0, 0, 0},
                                                     {SYS_SHAPEQUAD, 0, 0, 0, /* 71 */
                                                      SYS_ELEM_MEMBRANE, 0, 0, 0},
                                                     {SYS_SHAPETRI, 3, 0, 0, SYS_ELEM_MEMBRANE, 0, 1, 0},
                                                     {SYS_SHAPETRI, 4, 0, 0, SYS_ELEM_MEMBRANE, 0, 2, 0},
                                                     {SYS_SHAPETRI, 0, 0, 0, SYS_ELEM_MEMBRANE, 0, 0, 0},
                                                     {SYS_SHAPEQUAD, 3, 0, 0, SYS_ELEM_MEMBRANE, 0, 1, 0},
                                                     {SYS_SHAPEQUAD, 4, 0, 0, SYS_ELEM_MEMBRANE, 0, 2, 0},
                                                     {SYS_SHAPEPOINT, 0, 0, 0, SYS_ELEM_UNDEFINED, 0, 0, 0},
                                                     {SYS_SHAPEPOINT, 0, 0, 0, SYS_ELEM_UNDEFINED, 0, 0, 0},
                                                     {SYS_SHAPEPOINT, 0, 0, 0, SYS_ELEM_UNDEFINED, 0, 0, 0},
                                                     {SYS_SHAPEPOINT, 0, 0, 0, SYS_ELEM_UNDEFINED, 0, 0, 0},
                                                     {SYS_SHAPETRI, 0, 0, 0, /* 81 */
                                                      SYS_ELEM_SOLID, SYS_AXISYMMETRIC, 0, 0},
                                                     {SYS_SHAPETRI, 3, 0, 0, SYS_ELEM_SOLID, SYS_AXISYMMETRIC, 1, 0},
                                                     {SYS_SHAPEPOINT, 0, 0, 0, SYS_ELEM_UNDEFINED, 0, 0, 0},
                                                     {SYS_SHAPEQUAD, 0, 0, 0, SYS_ELEM_SOLID, SYS_AXISYMMETRIC, 0, 0},
                                                     {SYS_SHAPEQUAD, 3, 0, 0, SYS_ELEM_SOLID, SYS_AXISYMMETRIC, 1, 0},
                                                     {SYS_SHAPEPOINT, 0, 0, 0, SYS_ELEM_UNDEFINED, 0, 0, 0},
                                                     {SYS_SHAPEPOINT, 0, 0, 0, SYS_ELEM_UNDEFINED, 0, 0, 0},
                                                     {SYS_SHAPEPOINT, 0, 0, 0, SYS_ELEM_UNDEFINED, 0, 0, 0},
                                                     {SYS_SHAPEPOINT, 0, 0, 0, SYS_ELEM_UNDEFINED, 0, 0, 0},
                                                     {SYS_SHAPEPOINT, 0, 0, 0, SYS_ELEM_UNDEFINED, 0, 0, 0},
                                                     {SYS_SHAPETRI, 0, 0, 0, /* 91 */
                                                      SYS_ELEM_SHELL, 0, 0, SYS_ELEMSYS_FIRSTEDGE},
                                                     {SYS_SHAPETRI, 3, 0, 0, SYS_ELEM_SHELL, 0, 1, SYS_ELEMSYS_FIRSTEDGE},
                                                     {SYS_SHAPETRI, 4, 0, 0, SYS_ELEM_SHELL, 0, 2, SYS_ELEMSYS_FIRSTEDGE},
                                                     {SYS_SHAPEQUAD, 0, 0, 0, SYS_ELEM_SHELL, 0, 0, SYS_ELEMSYS_STANDARD},
                                                     {SYS_SHAPEQUAD, 3, 0, 0, SYS_ELEM_SHELL, 0, 1, SYS_ELEMSYS_STANDARD},
                                                     {SYS_SHAPEQUAD, 4, 0, 0, SYS_ELEM_SHELL, 0, 2, SYS_ELEMSYS_STANDARD},
                                                     {SYS_SHAPEPOINT, 0, 0, 0, SYS_ELEM_UNDEFINED, 0, 0, 0},
                                                     {SYS_SHAPEPOINT, 0, 0, 0, SYS_ELEM_UNDEFINED, 0, 0, 0},
                                                     {SYS_SHAPEPOINT, 0, 0, 0, SYS_ELEM_UNDEFINED, 0, 0, 0},
                                                     {SYS_SHAPEPOINT, 0, 0, 0, SYS_ELEM_UNDEFINED, 0, 0, 0},
                                                     {SYS_SHAPEWED, 2, 0, 0, /* 101 */
                                                      SYS_ELEM_SOLID, 0, 0, 0},
                                                     {SYS_SHAPEWED, 3, 0, 2, SYS_ELEM_SOLID, 0, 3, 0},
                                                     {SYS_SHAPEWED, 4, 0, 2, SYS_ELEM_SOLID, 0, 4, 0},
                                                     {SYS_SHAPEHEX, 2, 0, 0, SYS_ELEM_SOLID, 0, 0, 0},
                                                     {SYS_SHAPEHEX, 3, 0, 2, SYS_ELEM_SOLID, 0, 3, 0},
                                                     {SYS_SHAPEHEX, 4, 0, 2, SYS_ELEM_SOLID, 0, 4, 0},
                                                     {SYS_SHAPEPOINT, 0, 0, 0, SYS_ELEM_UNDEFINED, 0, 0, 0},
                                                     {SYS_SHAPEPOINT, 0, 0, 0, SYS_ELEM_UNDEFINED, 0, 0, 0},
                                                     {SYS_SHAPEPOINT, 0, 0, 0, SYS_ELEM_UNDEFINED, 0, 0, 0},
                                                     {SYS_SHAPEPOINT, 0, 0, 0, SYS_ELEM_UNDEFINED, 0, 0, 0},
                                                     {SYS_SHAPETET, 0, 0, 0, /* 111 */
                                                      SYS_ELEM_SOLID, 0, 0, 0},
                                                     {SYS_SHAPEWED, 0, 0, 0, SYS_ELEM_SOLID, 0, 0, 0},
                                                     {SYS_SHAPEWED, 3, 0, 0, SYS_ELEM_SOLID, 0, 1, 0},
                                                     {SYS_SHAPEWED, 4, 0, 0, SYS_ELEM_SOLID, 0, 2, 0},
                                                     {SYS_SHAPEHEX, 0, 0, 0, SYS_ELEM_SOLID, 0, 0, 0},
                                                     {SYS_SHAPEHEX, 3, 0, 0, SYS_ELEM_SOLID, 0, 1, 0},
                                                     {SYS_SHAPEHEX, 4, 0, 0, SYS_ELEM_SOLID, 0, 2, 0},
                                                     {SYS_SHAPETET, 3, 0, 0, SYS_ELEM_SOLID, 0, 1, 0},
                                                     {SYS_SHAPEPYR, 0, 0, 0, SYS_ELEM_SOLID, 0, 0, 0},
                                                     {SYS_SHAPEPYR, 3, 0, 0, SYS_ELEM_SOLID, 0, 1, 0},
                                                     {SYS_SHAPELINE, 0, 0, 0, /* 121 */
                                                      SYS_ELEM_RIGID, 0, 0, 0},
                                                     {SYS_SHAPEPOINT, 0, 0, 0, SYS_ELEM_RIGID, 0, 0, 0},
                                                     {SYS_SHAPEPOINT, 0, 0, 0, SYS_ELEM_UNDEFINED, 0, 0, 0},
                                                     {SYS_SHAPEPOINT, 0, 0, 0, SYS_ELEM_UNDEFINED, 0, 0, 0},
                                                     {SYS_SHAPEPYR, 4, 0, 0, SYS_ELEM_SOLID, 0, 2, 0},
                                                     {SYS_SHAPETET, 4, 0, 0, SYS_ELEM_SOLID, 0, 5, 0},
                                                     {SYS_SHAPEPOINT, 0, 0, 0, SYS_ELEM_UNDEFINED, 0, 0, 0},
                                                     {SYS_SHAPEPOINT, 0, 0, 0, SYS_ELEM_UNDEFINED, 0, 0, 0},
                                                     {SYS_SHAPEPOINT, 0, 0, 0, SYS_ELEM_UNDEFINED, 0, 0, 0},
                                                     {SYS_SHAPEPOINT, 0, 0, 0, SYS_ELEM_UNDEFINED, 0, 0, 0},
                                                     {SYS_SHAPEPOINT, 0, 0, 0, /* 131 */
                                                      SYS_ELEM_UNDEFINED, 0, 0, 0},
                                                     {SYS_SHAPEPOINT, 0, 0, 0, SYS_ELEM_UNDEFINED, 0, 0, 0},
                                                     {SYS_SHAPEPOINT, 0, 0, 0, SYS_ELEM_UNDEFINED, 0, 0, 0},
                                                     {SYS_SHAPEPOINT, 0, 0, 0, SYS_ELEM_UNDEFINED, 0, 0, 0},
                                                     {SYS_SHAPEPOINT, 0, 0, 0, SYS_ELEM_UNDEFINED, 0, 0, 0},
                                                     {SYS_SHAPELINE, 0, 0, 0, SYS_ELEM_SPRINGDASHPOT, 0, 0, 0},
                                                     {SYS_SHAPELINE, 0, 0, 0, SYS_ELEM_SPRINGDASHPOT, 0, 0, 0},
                                                     {SYS_SHAPEPOINT, 1, 0, 0, SYS_ELEM_SPRINGDASHPOT, 0, 0, 0},
                                                     {SYS_SHAPEPOINT, 1, 0, 0, SYS_ELEM_SPRINGDASHPOT, 0, 0, 0},
                                                     {SYS_SHAPEPOINT, 0, 0, 0, SYS_ELEM_UNDEFINED, 0, 0, 0},
                                                     {SYS_SHAPELINE, 0, 0, 0, /* 141 */
                                                      SYS_ELEM_SPRINGDASHPOT, 0, 0, 0},
                                                     {SYS_SHAPEPOINT, 1, 0, 0, SYS_ELEM_SPRINGDASHPOT, 0, 0, 0},
                                                     {SYS_SHAPEPOINT, 0, 0, 0, SYS_ELEM_UNDEFINED, 0, 0, 0},
                                                     {SYS_SHAPEPOINT, 0, 0, 0, SYS_ELEM_UNDEFINED, 0, 0, 0},
                                                     {SYS_SHAPEPOINT, 0, 0, 0, SYS_ELEM_UNDEFINED, 0, 0, 0},
                                                     {SYS_SHAPEPOINT, 0, 0, 0, SYS_ELEM_UNDEFINED, 0, 0, 0},
                                                     {SYS_SHAPEPOINT, 0, 0, 0, SYS_ELEM_UNDEFINED, 0, 0, 0},
                                                     {SYS_SHAPEPOINT, 0, 0, 0, SYS_ELEM_UNDEFINED, 0, 0, 0},
                                                     {SYS_SHAPEPOINT, 0, 0, 0, SYS_ELEM_UNDEFINED, 0, 0, 0},
                                                     {SYS_SHAPEPOINT, 0, 0, 0, SYS_ELEM_UNDEFINED, 0, 0, 0},
                                                     {SYS_SHAPELINE, 0, 0, 0, /* 151 */
                                                      SYS_ELEM_GAP, 0, 0, 0},
                                                     {SYS_SHAPEPOINT, 1, 0, 0, SYS_ELEM_GAP, 0, 0, 0},
                                                     {SYS_SHAPEPOINT, 0, 0, 0, SYS_ELEM_UNDEFINED, 0, 0, 0},
                                                     {SYS_SHAPEPOINT, 0, 0, 0, SYS_ELEM_UNDEFINED, 0, 0, 0},
                                                     {SYS_SHAPEPOINT, 0, 0, 0, SYS_ELEM_UNDEFINED, 0, 0, 0},
                                                     {SYS_SHAPEPOINT, 0, 0, 0, SYS_ELEM_UNDEFINED, 0, 0, 0},
                                                     {SYS_SHAPEPOINT, 0, 0, 0, SYS_ELEM_UNDEFINED, 0, 0, 0},
                                                     {SYS_SHAPEPOINT, 0, 0, 0, SYS_ELEM_UNDEFINED, 0, 0, 0},
                                                     {SYS_SHAPEPOINT, 0, 0, 0, SYS_ELEM_UNDEFINED, 0, 0, 0},
                                                     {SYS_SHAPEPOINT, 0, 0, 0, SYS_ELEM_UNDEFINED, 0, 0, 0},
                                                     {SYS_SHAPEPOINT, 0, 0, 0, /* 161 */
                                                      SYS_ELEM_MASS, 0, 0, 0},
                                                     {SYS_SHAPEPOINT, 0, 0, 0, SYS_ELEM_UNDEFINED, 0, 0, 0},
                                                     {SYS_SHAPEPOINT, 0, 0, 0, SYS_ELEM_UNDEFINED, 0, 0, 0},
                                                     {SYS_SHAPEPOINT, 0, 0, 0, SYS_ELEM_UNDEFINED, 0, 0, 0},
                                                     {SYS_SHAPEPOINT, 0, 0, 0, SYS_ELEM_UNDEFINED, 0, 0, 0},
                                                     {SYS_SHAPEPOINT, 0, 0, 0, SYS_ELEM_UNDEFINED, 0, 0, 0},
                                                     {SYS_SHAPEPOINT, 0, 0, 0, SYS_ELEM_UNDEFINED, 0, 0, 0},
                                                     {SYS_SHAPEPOINT, 0, 0, 0, SYS_ELEM_UNDEFINED, 0, 0, 0},
                                                     {SYS_SHAPEPOINT, 0, 0, 0, SYS_ELEM_UNDEFINED, 0, 0, 0},
                                                     {SYS_SHAPEPOINT, 0, 0, 0, SYS_ELEM_UNDEFINED, 0, 0, 0},
                                                     {SYS_SHAPELINE, 0, 0, 0, /* 171 */
                                                      SYS_ELEM_SHELL, SYS_AXISYMMETRIC, 0, 0},
                                                     {SYS_SHAPELINE, 3, 0, 0, SYS_ELEM_SHELL, SYS_AXISYMMETRIC, 0, 0},
                                                     {SYS_SHAPEPOINT, 0, 0, 0, SYS_ELEM_UNDEFINED, 0, 0, 0},
                                                     {SYS_SHAPEPOINT, 0, 0, 0, SYS_ELEM_UNDEFINED, 0, 0, 0},
                                                     {SYS_SHAPEPOINT, 0, 0, 0, SYS_ELEM_UNDEFINED, 0, 0, 0},
                                                     {SYS_SHAPEPOINT, 0, 0, 0, SYS_ELEM_UNDEFINED, 0, 0, 0},
                                                     {SYS_SHAPEPOINT, 0, 0, 0, SYS_ELEM_UNDEFINED, 0, 0, 0},
                                                     {SYS_SHAPEPOINT, 0, 0, 0, SYS_ELEM_UNDEFINED, 0, 0, 0},
                                                     {SYS_SHAPEPOINT, 0, 0, 0, SYS_ELEM_UNDEFINED, 0, 0, 0},
                                                     {SYS_SHAPEPOINT, 0, 0, 0, SYS_ELEM_UNDEFINED, 0, 0, 0},
                                                     {SYS_SHAPEPOINT, 0, 0, 0, /* 181 */
                                                      SYS_ELEM_CONSTRAINT, 0, 0, 0},
                                                     {SYS_SHAPEPOINT, 0, 0, 0, SYS_ELEM_UNDEFINED, 0, 0, 0},
                                                     {SYS_SHAPEPOINT, 0, 0, 0, SYS_ELEM_UNDEFINED, 0, 0, 0},
                                                     {SYS_SHAPEPOINT, 0, 0, 0, SYS_ELEM_UNDEFINED, 0, 0, 0},
                                                     {SYS_SHAPEPOINT, 0, 0, 0, SYS_ELEM_UNDEFINED, 0, 0, 0},
                                                     {SYS_SHAPEPOINT, 0, 0, 0, SYS_ELEM_UNDEFINED, 0, 0, 0},
                                                     {SYS_SHAPEPOINT, 0, 0, 0, SYS_ELEM_UNDEFINED, 0, 0, 0},
                                                     {SYS_SHAPEPOINT, 0, 0, 0, SYS_ELEM_UNDEFINED, 0, 0, 0},
                                                     {SYS_SHAPEPOINT, 0, 0, 0, SYS_ELEM_UNDEFINED, 0, 0, 0},
                                                     {SYS_SHAPEPOINT, 0, 0, 0, SYS_ELEM_UNDEFINED, 0, 0, 0},
                                                     {SYS_SHAPELINE, 0, 0, 0, /* 191 */
                                                      SYS_ELEM_RIGID, 0, 0, 0},
                                                     {SYS_SHAPELINE, 0, 0, 0, SYS_ELEM_RIGID, 0, 0, 0},
                                                     {SYS_SHAPELINE, 0, 0, 0, SYS_ELEM_RIGID, 0, 0, 0},
                                                     {SYS_SHAPELINE, 0, 0, 0, SYS_ELEM_RIGID, 0, 0, 0},
                                                     {SYS_SHAPELINE, 0, 0, 0, SYS_ELEM_RIGID, 0, 0, 0},
                                                     {SYS_SHAPELINE, 0, 0, 0, SYS_ELEM_RIGID, 0, 0, 0}};

#endif
