/* Abaqus header file */
#ifndef VDMABA_DEF
#define VDMABA_DEF

#include "sam/base/basedefs.h"

#define ABA_NUMELEMTYPES 226

typedef struct {
    const Vchar* name;
    Vint shape, maxi, maxj, maxk;
    Vint featyp, feaspc, featwo, iredir;
    Vint esys, antype;
} vdm_ABAFil_fetypes;

static const vdm_ABAFil_fetypes abatypes[ABA_NUMELEMTYPES] = {
/*00 */ {"AC1D2", SYS_SHAPELINE, 0, 0, 0, SYS_ELEM_TRUSS, 0, 0, 0, SYS_ELEMSYS_GLOBAL, SYS_ANALYSIS_ACOUSTIC},
/*01 */ {"AC1D3", SYS_SHAPELINE, 3, 0, 0, SYS_ELEM_TRUSS, 0, 0, 0, SYS_ELEMSYS_GLOBAL, SYS_ANALYSIS_ACOUSTIC},
/*02 */ {"AC2D3", SYS_SHAPETRI, 0, 0, 0, SYS_ELEM_SOLID, 0, 0, 0, SYS_ELEMSYS_GLOBAL, SYS_ANALYSIS_ACOUSTIC},
/*03 */ {"AC2D4", SYS_SHAPEQUAD, 0, 0, 0, SYS_ELEM_SOLID, 0, 0, 0, SYS_ELEMSYS_GLOBAL, SYS_ANALYSIS_ACOUSTIC},
/*04 */ {"AC2D6", SYS_SHAPETRI, 3, 0, 0, SYS_ELEM_SOLID, 0, 0, 1, SYS_ELEMSYS_GLOBAL, SYS_ANALYSIS_ACOUSTIC},
/*05 */ {"AC2D8", SYS_SHAPEQUAD, 3, 0, 0, SYS_ELEM_SOLID, 0, 0, 1, SYS_ELEMSYS_GLOBAL, SYS_ANALYSIS_ACOUSTIC},
/*06 */ {"AC3D4", SYS_SHAPETET, 0, 0, 0, SYS_ELEM_SOLID, 0, 0, 0, SYS_ELEMSYS_GLOBAL, SYS_ANALYSIS_ACOUSTIC},
/*07 */ {"AC3D6", SYS_SHAPEWED, 0, 0, 0, SYS_ELEM_SOLID, 0, 0, 0, SYS_ELEMSYS_GLOBAL, SYS_ANALYSIS_ACOUSTIC},
/*08 */ {"AC3D8", SYS_SHAPEHEX, 0, 0, 0, SYS_ELEM_SOLID, 0, 0, 0, SYS_ELEMSYS_GLOBAL, SYS_ANALYSIS_ACOUSTIC},
/*09 */ {"AC3D10", SYS_SHAPETET, 3, 0, 0, SYS_ELEM_SOLID, 0, 0, 1, SYS_ELEMSYS_GLOBAL, SYS_ANALYSIS_ACOUSTIC},
/*10 */ {"AC3D15", SYS_SHAPEWED, 3, 0, 0, SYS_ELEM_SOLID, 0, 0, 1, SYS_ELEMSYS_GLOBAL, SYS_ANALYSIS_ACOUSTIC},
/*11 */ {"AC3D20", SYS_SHAPEHEX, 3, 0, 0, SYS_ELEM_SOLID, 0, 0, 1, SYS_ELEMSYS_GLOBAL, SYS_ANALYSIS_ACOUSTIC},
/*12 */ {"ACAX3", SYS_SHAPETRI, 0, 0, 0, SYS_ELEM_SOLID, 0, SYS_AXISYMMETRIC, 0, SYS_ELEMSYS_GLOBAL, SYS_ANALYSIS_ACOUSTIC},
/*13 */ {"ACAX4", SYS_SHAPEQUAD, 0, 0, 0, SYS_ELEM_SOLID, 0, SYS_AXISYMMETRIC, 0, SYS_ELEMSYS_GLOBAL, SYS_ANALYSIS_ACOUSTIC},
/*14 */ {"ACAX6", SYS_SHAPETRI, 3, 0, 0, SYS_ELEM_SOLID, 0, SYS_AXISYMMETRIC, 1, SYS_ELEMSYS_GLOBAL, SYS_ANALYSIS_ACOUSTIC},
/*15 */ {"ACAX8", SYS_SHAPEQUAD, 3, 0, 0, SYS_ELEM_SOLID, 0, SYS_AXISYMMETRIC, 1, SYS_ELEMSYS_GLOBAL, SYS_ANALYSIS_ACOUSTIC},
/*16 */ {"ACIN2D2", SYS_SHAPELINE, 0, 0, 0, SYS_ELEM_INFINITE, 0, 0, 0, SYS_ELEMSYS_GLOBAL, SYS_ANALYSIS_ACOUSTIC},
/*17 */ {"ACIN2D3", SYS_SHAPELINE, 3, 0, 0, SYS_ELEM_INFINITE, 0, 0, 1, SYS_ELEMSYS_GLOBAL, SYS_ANALYSIS_ACOUSTIC},
/*18 */
{"ACINAX2", SYS_SHAPELINE, 0, 0, 0, SYS_ELEM_INFINITE, 0, SYS_AXISYMMETRIC, 0, SYS_ELEMSYS_GLOBAL, SYS_ANALYSIS_ACOUSTIC},
/*19 */
{"ACINAX3", SYS_SHAPELINE, 3, 0, 0, SYS_ELEM_INFINITE, 0, SYS_AXISYMMETRIC, 1, SYS_ELEMSYS_GLOBAL, SYS_ANALYSIS_ACOUSTIC},
/*20 */ {"ACIN3D3", SYS_SHAPETRI, 0, 0, 0, SYS_ELEM_SOLID, 0, SYS_AXISYMMETRIC, 0, SYS_ELEMSYS_GLOBAL, SYS_ANALYSIS_ACOUSTIC},
/*21 */ {"ACIN3D4", SYS_SHAPEQUAD, 0, 0, 0, SYS_ELEM_INFINITE, 0, 0, 0, SYS_ELEMSYS_GLOBAL, SYS_ANALYSIS_ACOUSTIC},
/*22 */ {"ACIN3D6", SYS_SHAPETRI, 3, 0, 0, SYS_ELEM_INFINITE, 0, 0, 0, SYS_ELEMSYS_GLOBAL, SYS_ANALYSIS_ACOUSTIC},
/*23 */ {"ACIN3D8", SYS_SHAPEQUAD, 3, 0, 0, SYS_ELEM_INFINITE, 0, 0, 0, SYS_ELEMSYS_GLOBAL, SYS_ANALYSIS_ACOUSTIC},
/*24 */ {"ASI1", SYS_SHAPEPOINT, 1, 0, 0, SYS_ELEM_INTER, 0, 0, 0, SYS_ELEMSYS_GLOBAL, SYS_ANALYSIS_ACOUSTIC},
/*25 */ {"ASI2A", SYS_SHAPELINE, 0, 0, 0, SYS_ELEM_INTER, 0, SYS_AXISYMMETRIC, 0, SYS_ELEMSYS_GLOBAL, SYS_ANALYSIS_ACOUSTIC},
/*26 */ {"ASI2", SYS_SHAPELINE, 0, 0, 0, SYS_ELEM_INTER, 0, 0, 0, SYS_ELEMSYS_GLOBAL, SYS_ANALYSIS_ACOUSTIC},
/*27 */ {"ASI3A", SYS_SHAPELINE, 3, 0, 0, SYS_ELEM_INTER, 0, SYS_AXISYMMETRIC, 0, SYS_ELEMSYS_GLOBAL, SYS_ANALYSIS_ACOUSTIC},
/*28 */ {"ASI3", SYS_SHAPELINE, 3, 0, 0, SYS_ELEM_INTER, 0, 0, 0, SYS_ELEMSYS_GLOBAL, SYS_ANALYSIS_ACOUSTIC},
/*29 */ {"ASI4", SYS_SHAPEQUAD, 0, 0, 0, SYS_ELEM_INTER, 0, 0, 0, SYS_ELEMSYS_GLOBAL, SYS_ANALYSIS_ACOUSTIC},
/*30 */ {"ASI8", SYS_SHAPEQUAD, 3, 0, 0, SYS_ELEM_INTER, 0, 0, 1, SYS_ELEMSYS_GLOBAL, SYS_ANALYSIS_ACOUSTIC},
/*31 */ {"STRI3", SYS_SHAPETRI, 0, 0, 0, SYS_ELEM_SHELL, 0, 0, 0, SYS_ELEMSYS_GLOBALPROJECT, SYS_ANALYSIS_STRUCTURAL},
/*32 */ {"S3", SYS_SHAPETRI, 0, 0, 0, SYS_ELEM_SHELL, 0, 0, 0, SYS_ELEMSYS_GLOBALPROJECT, SYS_ANALYSIS_STRUCTURAL},
/*33 */ {"S4", SYS_SHAPEQUAD, 0, 0, 0, SYS_ELEM_SHELL, 0, 0, 0, SYS_ELEMSYS_GLOBALPROJECT, SYS_ANALYSIS_STRUCTURAL},
/*34 */ {"CPS3", SYS_SHAPETRI, 0, 0, 0, SYS_ELEM_SOLID, 0, SYS_PLANESTRESS, 1, SYS_ELEMSYS_GLOBAL, SYS_ANALYSIS_STRUCTURAL},
/*35 */ {"CPS8", SYS_SHAPEQUAD, 3, 0, 0, SYS_ELEM_SOLID, 0, SYS_PLANESTRESS, 1, SYS_ELEMSYS_GLOBAL, SYS_ANALYSIS_STRUCTURAL},
/*36 */ {"CPS4", SYS_SHAPEQUAD, 0, 0, 0, SYS_ELEM_SOLID, 0, SYS_PLANESTRESS, 0, SYS_ELEMSYS_GLOBAL, SYS_ANALYSIS_STRUCTURAL},
/*37 */ {"S9R5", SYS_SHAPEQUAD, 3, 3, 0, SYS_ELEM_SHELL, 0, 0, 2, SYS_ELEMSYS_GLOBALPROJECT, SYS_ANALYSIS_STRUCTURAL},
/*38 */ {"S8R", SYS_SHAPEQUAD, 3, 0, 0, SYS_ELEM_SHELL, 0, 0, 1, SYS_ELEMSYS_GLOBALPROJECT, SYS_ANALYSIS_STRUCTURAL},
/*39 */ {"CPS6", SYS_SHAPETRI, 3, 0, 0, SYS_ELEM_SOLID, 0, SYS_PLANESTRESS, 1, SYS_ELEMSYS_GLOBAL, SYS_ANALYSIS_STRUCTURAL},
/*40 */ {"STRI65", SYS_SHAPETRI, 3, 0, 0, SYS_ELEM_SHELL, 0, 0, 1, SYS_ELEMSYS_GLOBALPROJECT, SYS_ANALYSIS_STRUCTURAL},
/*41 */ {"MASS", SYS_SHAPEPOINT, 1, 0, 0, SYS_ELEM_MASS, 0, 0, 0, SYS_ELEMSYS_GLOBAL, SYS_ANALYSIS_STRUCTURAL},
/*42 */ {"ROTARYI", SYS_SHAPEPOINT, 1, 0, 0, SYS_ELEM_MASS, 0, 0, 0, SYS_ELEMSYS_GLOBAL, SYS_ANALYSIS_STRUCTURAL},
/*43 */ {"B31", SYS_SHAPELINE, 0, 0, 0, SYS_ELEM_BEAM, 0, 0, 0, SYS_ELEMSYS_GLOBALPROJECT, SYS_ANALYSIS_STRUCTURAL},
/*44 */ {"B32", SYS_SHAPELINE, 3, 0, 0, SYS_ELEM_BEAM, 0, 0, 0, SYS_ELEMSYS_GLOBALPROJECT, SYS_ANALYSIS_STRUCTURAL},
/*45 */ {"B33", SYS_SHAPELINE, 0, 0, 0, SYS_ELEM_BEAM, 0, 0, 0, SYS_ELEMSYS_GLOBALPROJECT, SYS_ANALYSIS_STRUCTURAL},
/*46 */ {"B34", SYS_SHAPELINE, 0, 0, 0, SYS_ELEM_BEAM, 0, 0, 0, SYS_ELEMSYS_GLOBALPROJECT, SYS_ANALYSIS_STRUCTURAL},
/*47 */ {"B21", SYS_SHAPELINE, 0, 0, 0, SYS_ELEM_BEAM, 0, 0, 0, SYS_ELEMSYS_GLOBALPROJECT, SYS_ANALYSIS_STRUCTURAL},
/*48 */ {"B22", SYS_SHAPELINE, 3, 0, 0, SYS_ELEM_BEAM, 0, 0, 0, SYS_ELEMSYS_GLOBALPROJECT, SYS_ANALYSIS_STRUCTURAL},
/*49 */ {"B23", SYS_SHAPELINE, 0, 0, 0, SYS_ELEM_BEAM, 0, 0, 0, SYS_ELEMSYS_GLOBALPROJECT, SYS_ANALYSIS_STRUCTURAL},
/*50 */ {"T2D2", SYS_SHAPELINE, 0, 0, 0, SYS_ELEM_TRUSS, 0, 0, 0, SYS_ELEMSYS_GLOBAL, SYS_ANALYSIS_STRUCTURAL},
/*51 */ {"T2D3", SYS_SHAPELINE, 3, 0, 0, SYS_ELEM_TRUSS, 0, 0, 0, SYS_ELEMSYS_GLOBAL, SYS_ANALYSIS_STRUCTURAL},
/*52 */ {"T3D2", SYS_SHAPELINE, 0, 0, 0, SYS_ELEM_TRUSS, 0, 0, 0, SYS_ELEMSYS_GLOBAL, SYS_ANALYSIS_STRUCTURAL},
/*53 */ {"T3D3", SYS_SHAPELINE, 3, 0, 0, SYS_ELEM_TRUSS, 0, 0, 0, SYS_ELEMSYS_GLOBAL, SYS_ANALYSIS_STRUCTURAL},
/*54 */ {"C3D4", SYS_SHAPETET, 2, 0, 0, SYS_ELEM_SOLID, 0, 0, 0, SYS_ELEMSYS_GLOBAL, SYS_ANALYSIS_STRUCTURAL},
/*55 */ {"C3D5", SYS_SHAPEPYR, 0, 0, 0, SYS_ELEM_SOLID, 0, 0, 0, SYS_ELEMSYS_GLOBAL, SYS_ANALYSIS_STRUCTURAL},
/*56 */ {"C3D6", SYS_SHAPEWED, 0, 0, 0, SYS_ELEM_SOLID, 0, 0, 0, SYS_ELEMSYS_GLOBAL, SYS_ANALYSIS_STRUCTURAL},
/*57 */ {"C3D8", SYS_SHAPEHEX, 0, 0, 0, SYS_ELEM_SOLID, 0, 0, 0, SYS_ELEMSYS_GLOBAL, SYS_ANALYSIS_STRUCTURAL},
/*58 */ {"C3D10", SYS_SHAPETET, 3, 0, 0, SYS_ELEM_SOLID, 0, 0, 1, SYS_ELEMSYS_GLOBAL, SYS_ANALYSIS_STRUCTURAL},
/*59 */ {"C3D15V", SYS_SHAPEWED, 3, 3, 3, SYS_ELEM_SOLID, 0, 0, 4, SYS_ELEMSYS_GLOBAL, SYS_ANALYSIS_STRUCTURAL},
/*60 */ {"C3D15", SYS_SHAPEWED, 3, 0, 0, SYS_ELEM_SOLID, 0, 0, 1, SYS_ELEMSYS_GLOBAL, SYS_ANALYSIS_STRUCTURAL},
/*61 */ {"C3D20", SYS_SHAPEHEX, 3, 0, 0, SYS_ELEM_SOLID, 0, 0, 1, SYS_ELEMSYS_GLOBAL, SYS_ANALYSIS_STRUCTURAL},
/*62 */ {"C3D27", SYS_SHAPEHEX, 3, 3, 3, SYS_ELEM_SOLID, 0, 0, 5, SYS_ELEMSYS_GLOBAL, SYS_ANALYSIS_STRUCTURAL},
/*63 */
{"CINPE4", SYS_SHAPEQUAD, 0, 0, 0, SYS_ELEM_INFINITE, 0, SYS_PLANESTRAIN, 0, SYS_ELEMSYS_GLOBAL, SYS_ANALYSIS_STRUCTURAL},
/*64 */
{"CINPE5", SYS_SHAPEQUAD, 3, 0x000e0000, 0, SYS_ELEM_INFINITE, 0, SYS_PLANESTRAIN, 0, SYS_ELEMSYS_GLOBAL,
 SYS_ANALYSIS_STRUCTURAL},
/*65 */
{"CINAX4", SYS_SHAPEQUAD, 0, 0, 0, SYS_ELEM_INFINITE, 0, SYS_AXISYMMETRIC, 0, SYS_ELEMSYS_GLOBAL, SYS_ANALYSIS_STRUCTURAL},
/*66 */
{"CINAX5", SYS_SHAPEQUAD, 3, 0x000e0000, 0, SYS_ELEM_INFINITE, 0, SYS_AXISYMMETRIC, 0, SYS_ELEMSYS_GLOBAL,
 SYS_ANALYSIS_STRUCTURAL},
/*67 */
{"CINPS4", SYS_SHAPEQUAD, 0, 0, 0, SYS_ELEM_INFINITE, 0, SYS_PLANESTRESS, 0, SYS_ELEMSYS_GLOBAL, SYS_ANALYSIS_STRUCTURAL},
/*68 */
{"CINPS5", SYS_SHAPEQUAD, 3, 0x000e0000, 0, SYS_ELEM_INFINITE, 0, SYS_PLANESTRESS, 0, SYS_ELEMSYS_GLOBAL,
 SYS_ANALYSIS_STRUCTURAL},
/*69 */ {"CIN3D8", SYS_SHAPEHEX, 0, 0, 0, SYS_ELEM_INFINITE, 0, 0, 0, SYS_ELEMSYS_GLOBAL, SYS_ANALYSIS_STRUCTURAL},
/*70 */ {"CIN3D12", SYS_SHAPEHEX, 3, 0x0ff00000, 0, SYS_ELEM_INFINITE, 0, 0, 0, SYS_ELEMSYS_GLOBAL, SYS_ANALYSIS_STRUCTURAL},
/*71 */ {"CIN3D18", SYS_SHAPEHEX, 3, 3, 2, SYS_ELEM_INFINITE, 0, 0, 4, SYS_ELEMSYS_GLOBAL, SYS_ANALYSIS_STRUCTURAL},
/*72 */ {"CPE3", SYS_SHAPETRI, 0, 0, 0, SYS_ELEM_SOLID, 0, SYS_PLANESTRAIN, 0, SYS_ELEMSYS_GLOBAL, SYS_ANALYSIS_STRUCTURAL},
/*73 */ {"CPE4", SYS_SHAPEQUAD, 0, 0, 0, SYS_ELEM_SOLID, 0, SYS_PLANESTRAIN, 0, SYS_ELEMSYS_GLOBAL, SYS_ANALYSIS_STRUCTURAL},
/*74 */ {"CPE6", SYS_SHAPETRI, 3, 0, 0, SYS_ELEM_SOLID, 0, SYS_PLANESTRAIN, 1, SYS_ELEMSYS_GLOBAL, SYS_ANALYSIS_STRUCTURAL},
/*75 */ {"CPE8", SYS_SHAPEQUAD, 3, 0, 0, SYS_ELEM_SOLID, 0, SYS_PLANESTRAIN, 1, SYS_ELEMSYS_GLOBAL, SYS_ANALYSIS_STRUCTURAL},
/*76 */ {"CPEG3", SYS_SHAPETRI, 0, 0, 0, SYS_ELEM_SOLID, 0, SYS_PLANESTRAIN, 0, SYS_ELEMSYS_GLOBAL, SYS_ANALYSIS_STRUCTURAL},
/*77 */ {"CPEG4", SYS_SHAPEQUAD, 0, 0, 0, SYS_ELEM_SOLID, 0, SYS_PLANESTRAIN, 0, SYS_ELEMSYS_GLOBAL, SYS_ANALYSIS_STRUCTURAL},
/*78 */ {"CPEG6", SYS_SHAPETRI, 3, 0, 0, SYS_ELEM_SOLID, 0, SYS_PLANESTRAIN, 1, SYS_ELEMSYS_GLOBAL, SYS_ANALYSIS_STRUCTURAL},
/*79 */ {"CPEG8", SYS_SHAPEQUAD, 3, 0, 0, SYS_ELEM_SOLID, 0, SYS_PLANESTRAIN, 1, SYS_ELEMSYS_GLOBAL, SYS_ANALYSIS_STRUCTURAL},
/*80 */ {"CAX3", SYS_SHAPETRI, 0, 0, 0, SYS_ELEM_SOLID, 0, SYS_AXISYMMETRIC, 0, SYS_ELEMSYS_GLOBAL, SYS_ANALYSIS_STRUCTURAL},
/*81 */ {"CAX4", SYS_SHAPEQUAD, 0, 0, 0, SYS_ELEM_SOLID, 0, SYS_AXISYMMETRIC, 0, SYS_ELEMSYS_GLOBAL, SYS_ANALYSIS_STRUCTURAL},
/*82 */ {"CAX6", SYS_SHAPETRI, 3, 0, 0, SYS_ELEM_SOLID, 0, SYS_AXISYMMETRIC, 1, SYS_ELEMSYS_GLOBAL, SYS_ANALYSIS_STRUCTURAL},
/*83 */ {"CAX8", SYS_SHAPEQUAD, 3, 0, 0, SYS_ELEM_SOLID, 0, SYS_AXISYMMETRIC, 1, SYS_ELEMSYS_GLOBAL, SYS_ANALYSIS_STRUCTURAL},
/*84 */ {"CAXA4", SYS_SHAPEQUAD, 0, 0, 0, SYS_ELEM_SOLID, 0, SYS_AXISYMMETRIC, 0, SYS_ELEMSYS_GLOBAL, SYS_ANALYSIS_STRUCTURAL},
/*85 */ {"CAXA8", SYS_SHAPEQUAD, 3, 0, 0, SYS_ELEM_SOLID, 0, SYS_AXISYMMETRIC, 1, SYS_ELEMSYS_GLOBAL, SYS_ANALYSIS_STRUCTURAL},
/*86 */ {"CGAX3", SYS_SHAPETRI, 0, 0, 0, SYS_ELEM_SOLID, 0, SYS_AXISYMMETRIC, 0, SYS_ELEMSYS_GLOBAL, SYS_ANALYSIS_STRUCTURAL},
/*87 */ {"CGAX4", SYS_SHAPEQUAD, 0, 0, 0, SYS_ELEM_SOLID, 0, SYS_AXISYMMETRIC, 0, SYS_ELEMSYS_GLOBAL, SYS_ANALYSIS_STRUCTURAL},
/*88 */ {"CGAX6", SYS_SHAPETRI, 3, 0, 0, SYS_ELEM_SOLID, 0, SYS_AXISYMMETRIC, 1, SYS_ELEMSYS_GLOBAL, SYS_ANALYSIS_STRUCTURAL},
/*89 */ {"CGAX8", SYS_SHAPEQUAD, 3, 0, 0, SYS_ELEM_SOLID, 0, SYS_AXISYMMETRIC, 1, SYS_ELEMSYS_GLOBAL, SYS_ANALYSIS_STRUCTURAL},
/* 90*/ {"C1D2", SYS_SHAPELINE, 0, 0, 0, SYS_ELEM_TRUSS, 0, 0, 0, SYS_ELEMSYS_GLOBAL, SYS_ANALYSIS_STRUCTURAL},
/* 91*/ {"C1D3", SYS_SHAPELINE, 3, 0, 0, SYS_ELEM_TRUSS, 0, 0, 0, SYS_ELEMSYS_GLOBAL, SYS_ANALYSIS_STRUCTURAL},
/* 92*/
{"SAX1", SYS_SHAPELINE, 0, 0, 0, SYS_ELEM_SHELL, 0, SYS_AXISYMMETRIC, 0, SYS_ELEMSYS_GLOBALPROJECT, SYS_ANALYSIS_STRUCTURAL},
/* 93*/
{"SAX2", SYS_SHAPELINE, 3, 0, 0, SYS_ELEM_SHELL, 0, SYS_AXISYMMETRIC, 0, SYS_ELEMSYS_GLOBALPROJECT, SYS_ANALYSIS_STRUCTURAL},
/* 94*/
{"SAXA1", SYS_SHAPELINE, 0, 0, 0, SYS_ELEM_SHELL, 0, SYS_AXISYMMETRIC, 0, SYS_ELEMSYS_GLOBALPROJECT, SYS_ANALYSIS_STRUCTURAL},
/* 95*/
{"SAXA2", SYS_SHAPELINE, 3, 0, 0, SYS_ELEM_SHELL, 0, SYS_AXISYMMETRIC, 0, SYS_ELEMSYS_GLOBALPROJECT, SYS_ANALYSIS_STRUCTURAL},
/* 96*/ {"M3D3", SYS_SHAPETRI, 0, 0, 0, SYS_ELEM_MEMBRANE, 0, 0, 0, SYS_ELEMSYS_GLOBALPROJECT, SYS_ANALYSIS_STRUCTURAL},
/* 97*/ {"M3D4", SYS_SHAPEQUAD, 0, 0, 0, SYS_ELEM_MEMBRANE, 0, 0, 0, SYS_ELEMSYS_GLOBALPROJECT, SYS_ANALYSIS_STRUCTURAL},
/* 98*/ {"M3D6", SYS_SHAPETRI, 3, 0, 0, SYS_ELEM_MEMBRANE, 0, 0, 1, SYS_ELEMSYS_GLOBALPROJECT, SYS_ANALYSIS_STRUCTURAL},
/* 99*/ {"M3D8", SYS_SHAPEQUAD, 3, 0, 0, SYS_ELEM_MEMBRANE, 0, 0, 1, SYS_ELEMSYS_GLOBALPROJECT, SYS_ANALYSIS_STRUCTURAL},
/*100*/ {"M3D9", SYS_SHAPEQUAD, 3, 3, 0, SYS_ELEM_MEMBRANE, 0, 0, 1, SYS_ELEMSYS_GLOBALPROJECT, SYS_ANALYSIS_STRUCTURAL},
/*101*/
{"MAX1", SYS_SHAPELINE, 0, 0, 0, SYS_ELEM_MEMBRANE, 0, SYS_AXISYMMETRIC, 0, SYS_ELEMSYS_GLOBALPROJECT, SYS_ANALYSIS_STRUCTURAL},
/*102*/
{"MAX2", SYS_SHAPELINE, 3, 0, 0, SYS_ELEM_MEMBRANE, 0, SYS_AXISYMMETRIC, 0, SYS_ELEMSYS_GLOBALPROJECT, SYS_ANALYSIS_STRUCTURAL},
/*103*/
{"MGAX1", SYS_SHAPELINE, 0, 0, 0, SYS_ELEM_MEMBRANE, 0, SYS_AXISYMMETRIC, 0, SYS_ELEMSYS_GLOBALPROJECT, SYS_ANALYSIS_STRUCTURAL},
/*104*/
{"MGAX2", SYS_SHAPELINE, 3, 0, 0, SYS_ELEM_MEMBRANE, 0, SYS_AXISYMMETRIC, 0, SYS_ELEMSYS_GLOBALPROJECT, SYS_ANALYSIS_STRUCTURAL},
/*105*/ {"PIPE21", SYS_SHAPELINE, 0, 0, 0, SYS_ELEM_BEAM, 0, 0, 0, SYS_ELEMSYS_GLOBALPROJECT, SYS_ANALYSIS_STRUCTURAL},
/*106*/ {"PIPE22", SYS_SHAPELINE, 3, 0, 0, SYS_ELEM_BEAM, 0, 0, 0, SYS_ELEMSYS_GLOBALPROJECT, SYS_ANALYSIS_STRUCTURAL},
/*107*/ {"PIPE31", SYS_SHAPELINE, 0, 0, 0, SYS_ELEM_BEAM, 0, 0, 0, SYS_ELEMSYS_GLOBALPROJECT, SYS_ANALYSIS_STRUCTURAL},
/*108*/ {"PIPE32", SYS_SHAPELINE, 3, 0, 0, SYS_ELEM_BEAM, 0, 0, 0, SYS_ELEMSYS_GLOBALPROJECT, SYS_ANALYSIS_STRUCTURAL},
/*109*/ {"ELBOW31", SYS_SHAPELINE, 0, 0, 0, SYS_ELEM_BEAM, 0, 0, 0, SYS_ELEMSYS_GLOBALPROJECT, SYS_ANALYSIS_STRUCTURAL},
/*110*/ {"ELBOW32", SYS_SHAPELINE, 3, 0, 0, SYS_ELEM_BEAM, 0, 0, 0, SYS_ELEMSYS_GLOBALPROJECT, SYS_ANALYSIS_STRUCTURAL},
/*111*/
{"DASHPOTA", SYS_SHAPELINE, 0, 0, 0, SYS_ELEM_SPRINGDASHPOT, SYS_SPRINGDASHPOT_LINK, 0, 0, SYS_ELEMSYS_GLOBAL,
 SYS_ANALYSIS_STRUCTURAL},
/*112*/
{"DASHPOT1", SYS_SHAPEPOINT, 1, 0, 0, SYS_ELEM_SPRINGDASHPOT, SYS_SPRINGDASHPOT_VECTOR, 0, 0, SYS_ELEMSYS_GLOBAL,
 SYS_ANALYSIS_STRUCTURAL},
/*113*/
{"DASHPOT2", SYS_SHAPELINE, 0, 0, 0, SYS_ELEM_SPRINGDASHPOT, SYS_SPRINGDASHPOT_VECTOR, 0, 0, SYS_ELEMSYS_GLOBAL,
 SYS_ANALYSIS_STRUCTURAL},
/*114*/ {"F2D2", SYS_SHAPELINE, 0, 0, 0, SYS_ELEM_TRUSS, 0, 0, 0, SYS_ELEMSYS_GLOBAL, SYS_ANALYSIS_FLUID},
/*115*/ {"F3D3", SYS_SHAPETRI, 0, 0, 0, SYS_ELEM_MEMBRANE, 0, 0, 0, SYS_ELEMSYS_GLOBAL, SYS_ANALYSIS_FLUID},
/*116*/ {"F3D4", SYS_SHAPEQUAD, 0, 0, 0, SYS_ELEM_MEMBRANE, 0, 0, 0, SYS_ELEMSYS_GLOBAL, SYS_ANALYSIS_FLUID},
/*117*/ {"FAX2", SYS_SHAPELINE, 0, 0, 0, SYS_ELEM_MEMBRANE, 0, SYS_AXISYMMETRIC, 0, SYS_ELEMSYS_GLOBAL, SYS_ANALYSIS_FLUID},
/*118*/ {"FLINK", SYS_SHAPELINE, 0, 0, 0, SYS_ELEM_TRUSS, 0, 0, 0, SYS_ELEMSYS_GLOBAL, SYS_ANALYSIS_FLUID},
/*119*/ {"FC3D4", SYS_SHAPETET, 0, 0, 0, SYS_ELEM_SOLID, 0, 0, 0, SYS_ELEMSYS_GLOBAL, SYS_ANALYSIS_FLUID},
/*120*/ {"FC3D6", SYS_SHAPEWED, 0, 0, 0, SYS_ELEM_SOLID, 0, 0, 0, SYS_ELEMSYS_GLOBAL, SYS_ANALYSIS_FLUID},
/*121*/ {"FC3D8", SYS_SHAPEHEX, 0, 0, 0, SYS_ELEM_SOLID, 0, 0, 0, SYS_ELEMSYS_GLOBAL, SYS_ANALYSIS_FLUID},
/*122*/ {"FC3D10", SYS_SHAPETET, 3, 0, 0, SYS_ELEM_SOLID, 0, 0, 1, SYS_ELEMSYS_GLOBAL, SYS_ANALYSIS_FLUID},
/*123*/ {"FC3D15", SYS_SHAPEWED, 3, 0, 0, SYS_ELEM_SOLID, 0, 0, 1, SYS_ELEMSYS_GLOBAL, SYS_ANALYSIS_FLUID},
/*124*/ {"FC3D20", SYS_SHAPEHEX, 3, 0, 0, SYS_ELEM_SOLID, 0, 0, 1, SYS_ELEMSYS_GLOBAL, SYS_ANALYSIS_FLUID},
/*125*/ {"FRAME2D", SYS_SHAPELINE, 0, 0, 0, SYS_ELEM_BEAM, 0, 0, 0, SYS_ELEMSYS_GLOBALPROJECT, SYS_ANALYSIS_STRUCTURAL},
/*126*/ {"FRAME3D", SYS_SHAPELINE, 0, 0, 0, SYS_ELEM_BEAM, 0, 0, 0, SYS_ELEMSYS_GLOBALPROJECT, SYS_ANALYSIS_STRUCTURAL},
/*127*/ {"GAPUNI", SYS_SHAPELINE, 0, 0, 0, SYS_ELEM_GAP, 0, 0, 0, SYS_ELEMSYS_GLOBAL, SYS_ANALYSIS_STRUCTURAL},
/*128*/ {"HEATCAP", SYS_SHAPEPOINT, 1, 0, 0, SYS_ELEM_MASS, 0, 0, 0, SYS_ELEMSYS_GLOBAL, SYS_ANALYSIS_THERMAL},
/*129*/
{"ISL21A", SYS_SHAPELINE, 0, 0, 0, SYS_ELEM_INTER, SYS_INTER_CONTACT, SYS_AXISYMMETRIC, 0, SYS_ELEMSYS_GLOBAL,
 SYS_ANALYSIS_STRUCTURAL},
/*130*/
{"ISL22A", SYS_SHAPELINE, 3, 0, 0, SYS_ELEM_INTER, SYS_INTER_CONTACT, SYS_AXISYMMETRIC, 0, SYS_ELEMSYS_GLOBAL,
 SYS_ANALYSIS_STRUCTURAL},
/*131*/ {"ITS", SYS_SHAPELINE, 0, 0, 0, SYS_ELEM_SPRINGDASHPOT, 0, 0, 0, SYS_ELEMSYS_GLOBAL, SYS_ANALYSIS_STRUCTURAL},
/*132*/
{"JOINTC", SYS_SHAPELINE, 0, 0, 0, SYS_ELEM_SPRINGDASHPOT, SYS_SPRINGDASHPOT_BUSH, 0, 0, SYS_ELEMSYS_GLOBAL,
 SYS_ANALYSIS_STRUCTURAL},
/*133*/
{"SPRINGA", SYS_SHAPELINE, 0, 0, 0, SYS_ELEM_SPRINGDASHPOT, SYS_SPRINGDASHPOT_LINK, 0, 0, SYS_ELEMSYS_GLOBAL,
 SYS_ANALYSIS_STRUCTURAL},
/*134*/
{"SPRING1", SYS_SHAPEPOINT, 1, 0, 0, SYS_ELEM_SPRINGDASHPOT, SYS_SPRINGDASHPOT_VECTOR, 0, 0, SYS_ELEMSYS_GLOBAL,
 SYS_ANALYSIS_STRUCTURAL},
/*135*/
{"SPRING2", SYS_SHAPELINE, 0, 0, 0, SYS_ELEM_SPRINGDASHPOT, SYS_SPRINGDASHPOT_VECTOR, 0, 0, SYS_ELEMSYS_GLOBAL,
 SYS_ANALYSIS_STRUCTURAL},
/*136*/ {"R2D2", SYS_SHAPELINE, 0, 0, 0, SYS_ELEM_RIGID, 0, 0, 0, SYS_ELEMSYS_GLOBAL, SYS_ANALYSIS_STRUCTURAL},
/*137*/ {"R3D3", SYS_SHAPETRI, 0, 0, 0, SYS_ELEM_RIGID, 0, 0, 0, SYS_ELEMSYS_GLOBAL, SYS_ANALYSIS_STRUCTURAL},
/*138*/ {"R3D4", SYS_SHAPEQUAD, 0, 0, 0, SYS_ELEM_RIGID, 0, 0, 0, SYS_ELEMSYS_GLOBAL, SYS_ANALYSIS_STRUCTURAL},
/*139*/ {"RAX2", SYS_SHAPELINE, 0, 0, 0, SYS_ELEM_RIGID, 0, SYS_AXISYMMETRIC, 0, SYS_ELEMSYS_GLOBAL, SYS_ANALYSIS_STRUCTURAL},
/*140*/ {"RB2D2", SYS_SHAPELINE, 0, 0, 0, SYS_ELEM_RIGID, 0, 0, 0, SYS_ELEMSYS_GLOBAL, SYS_ANALYSIS_STRUCTURAL},
/*141*/ {"RB3D2", SYS_SHAPELINE, 0, 0, 0, SYS_ELEM_RIGID, 0, 0, 0, SYS_ELEMSYS_GLOBAL, SYS_ANALYSIS_STRUCTURAL},
/*142*/ {"DC1D2", SYS_SHAPELINE, 0, 0, 0, SYS_ELEM_TRUSS, 0, 0, 0, SYS_ELEMSYS_GLOBAL, SYS_ANALYSIS_THERMAL},
/*143*/ {"DC1D3", SYS_SHAPELINE, 3, 0, 0, SYS_ELEM_TRUSS, 0, 0, 0, SYS_ELEMSYS_GLOBAL, SYS_ANALYSIS_THERMAL},
/*144*/ {"DC2D3", SYS_SHAPETRI, 0, 0, 0, SYS_ELEM_SOLID, 0, SYS_PLANESTRAIN, 0, SYS_ELEMSYS_GLOBAL, SYS_ANALYSIS_THERMAL},
/*145*/ {"DC2D4", SYS_SHAPEQUAD, 0, 0, 0, SYS_ELEM_SOLID, 0, SYS_PLANESTRAIN, 0, SYS_ELEMSYS_GLOBAL, SYS_ANALYSIS_THERMAL},
/*146*/ {"DC2D6", SYS_SHAPETRI, 3, 0, 0, SYS_ELEM_SOLID, 0, SYS_PLANESTRAIN, 1, SYS_ELEMSYS_GLOBAL, SYS_ANALYSIS_THERMAL},
/*147*/ {"DC2D8", SYS_SHAPEQUAD, 3, 0, 0, SYS_ELEM_SOLID, 0, SYS_PLANESTRAIN, 1, SYS_ELEMSYS_GLOBAL, SYS_ANALYSIS_THERMAL},
/*148*/ {"DC3D4", SYS_SHAPETET, 0, 0, 0, SYS_ELEM_SOLID, 0, 0, 0, SYS_ELEMSYS_GLOBAL, SYS_ANALYSIS_THERMAL},
/*149*/ {"DC3D6", SYS_SHAPEWED, 0, 0, 0, SYS_ELEM_SOLID, 0, 0, 0, SYS_ELEMSYS_GLOBAL, SYS_ANALYSIS_THERMAL},
/*150*/ {"DC3D8", SYS_SHAPEHEX, 0, 0, 0, SYS_ELEM_SOLID, 0, 0, 0, SYS_ELEMSYS_GLOBAL, SYS_ANALYSIS_THERMAL},
/*151*/ {"DC3D10", SYS_SHAPETET, 3, 0, 0, SYS_ELEM_SOLID, 0, 0, 1, SYS_ELEMSYS_GLOBAL, SYS_ANALYSIS_THERMAL},
/*152*/ {"DC3D15", SYS_SHAPEWED, 3, 0, 0, SYS_ELEM_SOLID, 0, 0, 1, SYS_ELEMSYS_GLOBAL, SYS_ANALYSIS_THERMAL},
/*153*/ {"DC3D20", SYS_SHAPEHEX, 3, 0, 0, SYS_ELEM_SOLID, 0, 0, 1, SYS_ELEMSYS_GLOBAL, SYS_ANALYSIS_THERMAL},
/*154*/ {"DCAX3", SYS_SHAPETRI, 0, 0, 0, SYS_ELEM_SOLID, 0, SYS_AXISYMMETRIC, 0, SYS_ELEMSYS_GLOBAL, SYS_ANALYSIS_THERMAL},
/*155*/ {"DCAX4", SYS_SHAPEQUAD, 0, 0, 0, SYS_ELEM_SOLID, 0, SYS_AXISYMMETRIC, 0, SYS_ELEMSYS_GLOBAL, SYS_ANALYSIS_THERMAL},
/*156*/ {"DCAX6", SYS_SHAPETRI, 3, 0, 0, SYS_ELEM_SOLID, 0, SYS_AXISYMMETRIC, 1, SYS_ELEMSYS_GLOBAL, SYS_ANALYSIS_THERMAL},
/*157*/ {"DCAX8", SYS_SHAPEQUAD, 3, 0, 0, SYS_ELEM_SOLID, 0, SYS_AXISYMMETRIC, 1, SYS_ELEMSYS_GLOBAL, SYS_ANALYSIS_THERMAL},
/*158*/ {"DCC1D2", SYS_SHAPELINE, 0, 0, 0, SYS_ELEM_TRUSS, 0, 0, 0, SYS_ELEMSYS_GLOBAL, SYS_ANALYSIS_DIFFUSION},
/*159*/ {"DCC2D4", SYS_SHAPEQUAD, 0, 0, 0, SYS_ELEM_SOLID, 0, 0, 0, SYS_ELEMSYS_GLOBAL, SYS_ANALYSIS_DIFFUSION},
/*160*/ {"DCC3D8", SYS_SHAPEHEX, 0, 0, 0, SYS_ELEM_SOLID, 0, 0, 0, SYS_ELEMSYS_GLOBAL, SYS_ANALYSIS_DIFFUSION},
/*161*/ {"DCCAX2", SYS_SHAPELINE, 3, 0, 0, SYS_ELEM_SHELL, 0, SYS_AXISYMMETRIC, 0, SYS_ELEMSYS_GLOBAL, SYS_ANALYSIS_DIFFUSION},
/*162*/ {"DCCAX4", SYS_SHAPEQUAD, 0, 0, 0, SYS_ELEM_SOLID, 0, SYS_AXISYMMETRIC, 0, SYS_ELEMSYS_GLOBAL, SYS_ANALYSIS_DIFFUSION},
/*163*/ {"DGAP", SYS_SHAPELINE, 0, 0, 0, SYS_ELEM_GAP, 0, 0, 0, SYS_ELEMSYS_GLOBAL, SYS_ANALYSIS_THERMAL},
/*164*/ {"DS3", SYS_SHAPETRI, 0, 0, 0, SYS_ELEM_SHELL, 0, 0, 0, SYS_ELEMSYS_GLOBALPROJECT, SYS_ANALYSIS_THERMAL},
/*165*/ {"DS4", SYS_SHAPEQUAD, 0, 0, 0, SYS_ELEM_SHELL, 0, 0, 0, SYS_ELEMSYS_GLOBALPROJECT, SYS_ANALYSIS_THERMAL},
/*166*/ {"DS6", SYS_SHAPETRI, 3, 0, 0, SYS_ELEM_SHELL, 0, 0, 1, SYS_ELEMSYS_GLOBALPROJECT, SYS_ANALYSIS_THERMAL},
/*167*/ {"DS8", SYS_SHAPEQUAD, 3, 0, 0, SYS_ELEM_SHELL, 0, 0, 1, SYS_ELEMSYS_GLOBALPROJECT, SYS_ANALYSIS_THERMAL},
/*168*/ {"DSAX1", SYS_SHAPELINE, 0, 0, 0, SYS_ELEM_SHELL, 0, SYS_AXISYMMETRIC, 0, SYS_ELEMSYS_GLOBAL, SYS_ANALYSIS_THERMAL},
/*169*/ {"DSAX2", SYS_SHAPELINE, 3, 0, 0, SYS_ELEM_SHELL, 0, SYS_AXISYMMETRIC, 0, SYS_ELEMSYS_GLOBAL, SYS_ANALYSIS_THERMAL},
/*170*/ {"DCOUP", SYS_SHAPEPOINT, 1, 0, 0, SYS_ELEM_RIGID, SYS_RIGID_DIST, 0, 0, SYS_ELEMSYS_GLOBAL, SYS_ANALYSIS_STRUCTURAL},
/*171*/ {"IDCOUP", SYS_SHAPEPOINT, 1, 0, 0, SYS_ELEM_RIGID, SYS_RIGID_DIST, 0, 0, SYS_ELEMSYS_GLOBAL, SYS_ANALYSIS_STRUCTURAL},
/*172*/ {"DRAG2D", SYS_SHAPEPOINT, 1, 0, 0, SYS_ELEM_SPRINGDASHPOT, 0, 0, 0, SYS_ELEMSYS_GLOBAL, SYS_ANALYSIS_STRUCTURAL},
/*173*/ {"DRAG3D", SYS_SHAPEPOINT, 2, 0, 0, SYS_ELEM_SPRINGDASHPOT, 0, 0, 0, SYS_ELEMSYS_GLOBAL, SYS_ANALYSIS_STRUCTURAL},
/*174*/ {"CONN2D", SYS_SHAPELINE, 0, 0, 0, SYS_ELEM_UNDEFINED, 0, 0, 0, SYS_ELEMSYS_GLOBAL, SYS_ANALYSIS_STRUCTURAL},
/*175*/ {"CONN3D", SYS_SHAPELINE, 0, 0, 0, SYS_ELEM_UNDEFINED, 0, 0, 0, SYS_ELEMSYS_GLOBAL, SYS_ANALYSIS_STRUCTURAL},
/*176*/ {"CCL9", SYS_SHAPEWED, 2, 0, 3, SYS_ELEM_SOLID, 0, 0, 2, SYS_ELEMSYS_GLOBAL, SYS_SHAPEHEX},
/*177*/ {"CCL18", SYS_SHAPEWED, 3, 0, 3, SYS_ELEM_SOLID, 0, 0, 3, SYS_ELEMSYS_GLOBAL, SYS_SHAPEHEX},
/*178*/ {"CCL12", SYS_SHAPEHEX, 2, 0, 3, SYS_ELEM_SOLID, 0, 0, 2, SYS_ELEMSYS_GLOBAL, SYS_SHAPEHEX},
/*179*/ {"CCL24", SYS_SHAPEHEX, 3, 0, 3, SYS_ELEM_SOLID, 0, 0, 3, SYS_ELEMSYS_GLOBAL, SYS_SHAPEHEX},
/*180*/ {"MCL6", SYS_SHAPEQUAD, 2, 3, 0, SYS_ELEM_MEMBRANE, 0, 0, 3, SYS_ELEMSYS_GLOBALPROJECT, SYS_SHAPEHEX},
/*181*/ {"MCL9", SYS_SHAPEQUAD, 3, 3, 0, SYS_ELEM_MEMBRANE, 0, 0, 4, SYS_ELEMSYS_GLOBALPROJECT, SYS_SHAPEHEX},
/*182*/
{"SFMAX1", SYS_SHAPELINE, 0, 0, 0, SYS_ELEM_INTER, SYS_INTER_SURF, SYS_AXISYMMETRIC, 0, SYS_ELEMSYS_GLOBALPROJECT, SYS_SHAPEHEX},
/*183*/
{"SFMAX2", SYS_SHAPELINE, 3, 0, 0, SYS_ELEM_INTER, SYS_INTER_SURF, SYS_AXISYMMETRIC, 0, SYS_ELEMSYS_GLOBALPROJECT, SYS_SHAPEHEX},
/*184*/
{"SFMGAX1", SYS_SHAPELINE, 0, 0, 0, SYS_ELEM_INTER, SYS_INTER_SURF, SYS_AXISYMMETRIC, 0, SYS_ELEMSYS_GLOBALPROJECT, SYS_SHAPEHEX},
/*185*/
{"SFMGAX2", SYS_SHAPELINE, 3, 0, 0, SYS_ELEM_INTER, SYS_INTER_SURF, SYS_AXISYMMETRIC, 0, SYS_ELEMSYS_GLOBALPROJECT, SYS_SHAPEHEX},
/*186*/ {"SFM3D3", SYS_SHAPETRI, 0, 0, 0, SYS_ELEM_INTER, SYS_INTER_SURF, 0, 0, SYS_ELEMSYS_GLOBALPROJECT, SYS_SHAPEHEX},
/*187*/ {"SFM3D4", SYS_SHAPEQUAD, 0, 0, 0, SYS_ELEM_INTER, SYS_INTER_SURF, 0, 0, SYS_ELEMSYS_GLOBALPROJECT, SYS_SHAPEHEX},
/*188*/ {"SFM3D6", SYS_SHAPETRI, 3, 0, 0, SYS_ELEM_INTER, SYS_INTER_SURF, 0, 1, SYS_ELEMSYS_GLOBALPROJECT, SYS_SHAPEHEX},
/*189*/ {"SFM3D8", SYS_SHAPEQUAD, 3, 0, 0, SYS_ELEM_INTER, SYS_INTER_SURF, 0, 1, SYS_ELEMSYS_GLOBALPROJECT, SYS_SHAPEHEX},
/*190*/ {"SFMCL6", SYS_SHAPEQUAD, 2, 3, 0, SYS_ELEM_INTER, SYS_INTER_SURF, 0, 3, SYS_ELEMSYS_GLOBALPROJECT, SYS_SHAPEHEX},
/*191*/ {"SFMCL9", SYS_SHAPEQUAD, 3, 3, 0, SYS_ELEM_INTER, SYS_INTER_SURF, 0, 4, SYS_ELEMSYS_GLOBALPROJECT, SYS_SHAPEHEX},
/*192*/ {"GK2D2", SYS_SHAPELINE, 0, 0, 0, SYS_ELEM_INTER, SYS_INTER_GASKET, 0, 0, SYS_ELEMSYS_GLOBAL, SYS_ANALYSIS_STRUCTURAL},
/*193*/
{"GKPS4", SYS_SHAPEQUAD, 2, 2, 0, SYS_ELEM_INTER, SYS_INTER_GASKET, SYS_PLANESTRESS, 0, SYS_ELEMSYS_GLOBAL,
 SYS_ANALYSIS_STRUCTURAL},
/*194*/
{"GKPE4", SYS_SHAPEQUAD, 2, 2, 0, SYS_ELEM_INTER, SYS_INTER_GASKET, SYS_PLANESTRAIN, 0, SYS_ELEMSYS_GLOBAL,
 SYS_ANALYSIS_STRUCTURAL},
/*195*/
{"GKPS6", SYS_SHAPEQUAD, 3, 2, 0, SYS_ELEM_INTER, SYS_INTER_GASKET, SYS_PLANESTRESS, 0, SYS_ELEMSYS_GLOBAL,
 SYS_ANALYSIS_STRUCTURAL},
/*196*/
{"GKPE6", SYS_SHAPEQUAD, 3, 2, 0, SYS_ELEM_INTER, SYS_INTER_GASKET, SYS_PLANESTRAIN, 0, SYS_ELEMSYS_GLOBAL,
 SYS_ANALYSIS_STRUCTURAL},
/*197*/
{"GKAX2", SYS_SHAPELINE, 0, 0, 0, SYS_ELEM_INTER, SYS_INTER_GASKET, SYS_AXISYMMETRIC, 0, SYS_ELEMSYS_GLOBAL,
 SYS_ANALYSIS_STRUCTURAL},
/*198*/
{"GKAX4", SYS_SHAPEQUAD, 2, 2, 0, SYS_ELEM_INTER, SYS_INTER_GASKET, SYS_AXISYMMETRIC, 0, SYS_ELEMSYS_GLOBAL,
 SYS_ANALYSIS_STRUCTURAL},
/*199*/
{"GKAX6", SYS_SHAPEQUAD, 3, 2, 0, SYS_ELEM_INTER, SYS_INTER_GASKET, SYS_AXISYMMETRIC, 0, SYS_ELEMSYS_GLOBAL,
 SYS_ANALYSIS_STRUCTURAL},
/*200*/ {"GK3D2", SYS_SHAPELINE, 0, 0, 0, SYS_ELEM_INTER, SYS_INTER_GASKET, 0, 0, SYS_ELEMSYS_GLOBAL, SYS_ANALYSIS_STRUCTURAL},
/*201*/ {"GK3D4L", SYS_SHAPEQUAD, 2, 2, 0, SYS_ELEM_INTER, SYS_INTER_GASKET, 0, 0, SYS_ELEMSYS_GLOBAL, SYS_ANALYSIS_STRUCTURAL},
/*202*/ {"GK3D6L", SYS_SHAPEQUAD, 3, 2, 0, SYS_ELEM_INTER, SYS_INTER_GASKET, 0, 0, SYS_ELEMSYS_GLOBAL, SYS_ANALYSIS_STRUCTURAL},
/*203*/ {"GK3D6", SYS_SHAPEWED, 0, 0, 0, SYS_ELEM_INTER, SYS_INTER_GASKET, 0, 0, SYS_ELEMSYS_GLOBAL, SYS_ANALYSIS_STRUCTURAL},
/*204*/ {"GK3D8", SYS_SHAPEHEX, 0, 0, 0, SYS_ELEM_INTER, SYS_INTER_GASKET, 0, 0, SYS_ELEMSYS_GLOBAL, SYS_ANALYSIS_STRUCTURAL},
/*205*/ {"GK3D12", SYS_SHAPEWED, 3, 0, 2, SYS_ELEM_INTER, SYS_INTER_GASKET, 0, 0, SYS_ELEMSYS_GLOBAL, SYS_ANALYSIS_STRUCTURAL},
/*206*/ {"GK3D18", SYS_SHAPEHEX, 3, 3, 2, SYS_ELEM_INTER, SYS_INTER_GASKET, 0, 4, SYS_ELEMSYS_GLOBAL, SYS_ANALYSIS_STRUCTURAL},
/*207*/ {"Z", SYS_SHAPEPOINT, 1, 0, 0, SYS_ELEM_SUPER, 0, 0, 0, SYS_ELEMSYS_GLOBAL, SYS_ANALYSIS_STRUCTURAL},
/*208*/
{"SC6", SYS_SHAPEWED, 0, 0, 0, SYS_ELEM_SOLID, SYS_SOLID_SHELL, 0, 0, SYS_ELEMSYS_GLOBALPROJECTT, SYS_ANALYSIS_STRUCTURAL},
/*209*/
{"SC8", SYS_SHAPEHEX, 0, 0, 0, SYS_ELEM_SOLID, SYS_SOLID_SHELL, 0, 0, SYS_ELEMSYS_GLOBALPROJECTT, SYS_ANALYSIS_STRUCTURAL},
/*210*/
{"COH2D4P", SYS_SHAPEQUAD, 2, 3, 0, SYS_ELEM_INTER, SYS_INTER_COHESIVE, 0, 5, SYS_ELEMSYS_GLOBALPROJECTS,
 SYS_ANALYSIS_STRUCTURAL},
/*211*/
{"COH2D4", SYS_SHAPEQUAD, 0, 0, 0, SYS_ELEM_INTER, SYS_INTER_COHESIVE, 0, 0, SYS_ELEMSYS_GLOBALPROJECTS, SYS_ANALYSIS_STRUCTURAL},
/*212*/
{"COHAX4P", SYS_SHAPEQUAD, 2, 3, 0, SYS_ELEM_INTER, SYS_INTER_COHESIVE, SYS_AXISYMMETRIC, 5, SYS_ELEMSYS_GLOBALPROJECTS,
 SYS_ANALYSIS_STRUCTURAL},
/*213*/
{"COHAX4", SYS_SHAPEQUAD, 0, 0, 0, SYS_ELEM_INTER, SYS_INTER_COHESIVE, SYS_AXISYMMETRIC, 0, SYS_ELEMSYS_GLOBALPROJECTS,
 SYS_ANALYSIS_STRUCTURAL},
/*214*/
{"COH3D6P", SYS_SHAPEWED, 2, 0, 3, SYS_ELEM_INTER, SYS_INTER_COHESIVE, 0, 5, SYS_ELEMSYS_GLOBALPROJECTT, SYS_ANALYSIS_STRUCTURAL},
/*215*/
{"COH3D6", SYS_SHAPEWED, 0, 0, 0, SYS_ELEM_INTER, SYS_INTER_COHESIVE, 0, 0, SYS_ELEMSYS_GLOBALPROJECTT, SYS_ANALYSIS_STRUCTURAL},
/*216*/
{"COH3D8P", SYS_SHAPEHEX, 2, 0, 3, SYS_ELEM_INTER, SYS_INTER_COHESIVE, 0, 0, SYS_ELEMSYS_GLOBALPROJECTT, SYS_ANALYSIS_STRUCTURAL},
/*217*/
{"COH3D8", SYS_SHAPEHEX, 0, 0, 0, SYS_ELEM_INTER, SYS_INTER_COHESIVE, 0, 0, SYS_ELEMSYS_GLOBALPROJECTT, SYS_ANALYSIS_STRUCTURAL},
/*218*/ {"WARP2D3", SYS_SHAPETRI, 0, 0, 0, SYS_ELEM_SOLID, 0, SYS_PLANESTRESS, 0, SYS_ELEMSYS_GLOBAL, SYS_ANALYSIS_STRUCTURAL},
/*219*/ {"WARP2D4", SYS_SHAPEQUAD, 0, 0, 0, SYS_ELEM_SOLID, 0, SYS_PLANESTRESS, 0, SYS_ELEMSYS_GLOBAL, SYS_ANALYSIS_STRUCTURAL},
/*220*/ {"EC3D8", SYS_SHAPEHEX, 0, 0, 0, SYS_ELEM_SOLID, 0, 0, 0, SYS_ELEMSYS_GLOBAL, SYS_ANALYSIS_STRUCTURAL},
/* QEC => Coupled Thermal-Electrochemical/Coupled Thermal-Electrochemical/Coupled Thermal-Electrochemical-Structural/Coupled
   Thermal-Electrochemical-Structural-Pore Pressure */
/*221*/ {"QEC3D8", SYS_SHAPEHEX, 0, 0, 0, SYS_ELEM_SOLID, 0, 0, 0, SYS_ELEMSYS_GLOBAL, SYS_ANALYSIS_ELECTROCHEMICAL},
/*222*/ {"QEC3D6", SYS_SHAPEWED, 0, 0, 0, SYS_ELEM_SOLID, 0, 0, 0, SYS_ELEMSYS_GLOBAL, SYS_ANALYSIS_ELECTROCHEMICAL},
/*223*/ {"QEC3D4", SYS_SHAPETET, 0, 0, 0, SYS_ELEM_SOLID, 0, 0, 0, SYS_ELEMSYS_GLOBAL, SYS_ANALYSIS_ELECTROCHEMICAL},
/* Pyramid C3D13 doesn't exist in Abaqus but we need a dedicate topology*/
/*224*/ {"C3D13", SYS_SHAPEPYR, 3, 0, 0, SYS_ELEM_SOLID, 0, 0, 3, SYS_ELEMSYS_GLOBAL, SYS_ANALYSIS_STRUCTURAL},
/* Unknown must be the last */
/*225*/ {"UNKNOWN", SYS_SHAPEPOINT, 1, 0, 0, SYS_ELEM_RIGID, 0, 0, 0, SYS_ELEMSYS_GLOBAL, SYS_ANALYSIS_STRUCTURAL}};
#endif
