/* vdm output entries header file */
#ifndef ERFVAR_DEF
#define ERFVAR_DEF

#include "sam/base/basedefs.h"

static Vint mapten2d[3] = {1, 2, 4};
static Vint mapvec3d[3] = {1, 2, 3};
static Vint mapbm[3] = {4, 2, 3};
static Vint mapbf[3] = {1, 5, 6};
static Vint mapbr[3] = {4, 2, 3};
static Vint shellfor[3] = {1, 2, 3};
static Vint shellmom[3] = {4, 5, 6};
static Vint barfor[1] = {1};

#define PAM_LAYERPOSITION_BEAM1    9
#define PAM_LAYERPOSITION_BEAM2    10
#define PAM_LAYERPOSITION_BEAM3    11
#define PAM_LAYERPOSITION_BEAM4    12
#define PAM_LAYERPOSITION_BEAM12   13
#define PAM_LAYERPOSITION_BEAM13   14
#define PAM_LAYERPOSITION_BEAM14   15
#define PAM_LAYERPOSITION_BEAM23   16
#define PAM_LAYERPOSITION_BEAM24   17
#define PAM_LAYERPOSITION_BEAM34   18
#define PAM_LAYERPOSITION_BEAM123  19
#define PAM_LAYERPOSITION_BEAM124  20
#define PAM_LAYERPOSITION_BEAM234  21
#define PAM_LAYERPOSITION_BEAM134  22
#define PAM_LAYERPOSITION_BEAM1234 23

#define PAM_ERF_NONE      ((SYS_LAYERPOSITION_NONE << 8) + 1)
#define PAM_ERF_BOT       ((SYS_LAYERPOSITION_BOT << 8) + 1)
#define PAM_ERF_MID       ((SYS_LAYERPOSITION_MID << 8) + 1)
#define PAM_ERF_TOP       ((SYS_LAYERPOSITION_TOP << 8) + 1)
#define PAM_ERF_BOTTOP    ((SYS_LAYERPOSITION_BOTTOP << 8) + 2)
#define PAM_ERF_BOTMID    ((SYS_LAYERPOSITION_BOTMID << 8) + 2)
#define PAM_ERF_MIDTOP    ((SYS_LAYERPOSITION_MIDTOP << 8) + 2)
#define PAM_ERF_BOTMIDTOP ((SYS_LAYERPOSITION_BOTMIDTOP << 8) + 3)
#define PAM_ERF_BEAM1     ((PAM_LAYERPOSITION_BEAM1 << 8) + 1)
#define PAM_ERF_BEAM2     ((PAM_LAYERPOSITION_BEAM2 << 8) + 1)
#define PAM_ERF_BEAM3     ((PAM_LAYERPOSITION_BEAM3 << 8) + 1)
#define PAM_ERF_BEAM4     ((PAM_LAYERPOSITION_BEAM4 << 8) + 1)

typedef struct {
    Vchar* name;
    Vint rank;
    Vint node;
    Vint sect;
    Vint ncmp;
    Vint datatype;
    Vint offset;
    Vint* map;
    Vint restype;
    Vchar* cqua;
    Vint nqua;
    Vint iqua[SYS_NQUA_MAX];
    Vint ncoo;
    Vint ndim;
} vdm_PAMLib_ERFVarName;

static vdm_PAMLib_ERFVarName varnames[] = {
{(Vchar*)"THICKNESS", 0, 0, 0, 1, SYS_SCALAR, 0, NULL, SYS_RES_THICKNESS, (Vchar*)"", 0, {SYS_QUA_NONE, SYS_QUA_NONE}, 1, 0},
{(Vchar*)"RFORCE", 0, 0, 0, 1, SYS_SCALAR, 0, NULL, SYS_RES_FORCE, (Vchar*)"RESIDUAL", 1, {SYS_QUA_REL, SYS_QUA_NONE}, 1, 0},
{(Vchar*)"EPLE", 0, 0, 0, 1, SYS_SCALAR, 0, NULL, SYS_RES_E, (Vchar*)"", 2, {SYS_QUA_EQUIV, SYS_QUA_PLAST}, 1, 0},
{(Vchar*)"DISPLACEMENTS_NOD", 1, 0, 0, 6, SYS_VECTOR, 0, mapvec3d, SYS_RES_D, (Vchar*)"", 0, {SYS_QUA_NONE, SYS_QUA_NONE}, 3, 0},
{(Vchar*)"Velocity", 1, 0, 0, 6, SYS_VECTOR, 0, mapvec3d, SYS_RES_V, (Vchar*)"", 0, {SYS_QUA_NONE, SYS_QUA_NONE}, 3, 0},
{(Vchar*)"SPRING_Local_Force",
 1,
 0,
 0,
 6,
 SYS_VECTOR,
 0,
 mapvec3d,
 SYS_RES_FORCE,
 (Vchar*)"SPRING",
 1,
 {SYS_QUA_LOCAL, SYS_QUA_NONE},
 3,
 0},
{(Vchar*)"SPRING_Local_Moment",
 1,
 0,
 0,
 6,
 SYS_VECTOR,
 3,
 mapvec3d,
 SYS_RES_FORCE,
 (Vchar*)"SPRING",
 1,
 {SYS_QUA_LOCAL, SYS_QUA_NONE},
 3,
 0},
{(Vchar*)"Upper_Surface_engineering_Strain",
 2,
 0,
 PAM_ERF_TOP,
 6,
 SYS_TENSOR,
 0,
 NULL,
 SYS_RES_E,
 (Vchar*)"",
 0,
 {SYS_QUA_NONE, SYS_QUA_NONE},
 3,
 0},
{(Vchar*)"Membrane_Stress",
 2,
 0,
 PAM_ERF_MID,
 6,
 SYS_TENSOR,
 0,
 mapten2d,
 SYS_RES_S,
 (Vchar*)"",
 0,
 {SYS_QUA_NONE, SYS_QUA_NONE},
 3,
 0},
{(Vchar*)"Complex_Membrane_Stress",
 2,
 0,
 PAM_ERF_MID,
 6,
 SYS_TENSOR,
 0,
 mapten2d,
 SYS_RES_S,
 (Vchar*)"",
 0,
 {SYS_QUA_NONE, SYS_QUA_NONE},
 3,
 0},
{(Vchar*)"Acceleration", 1, 0, 0, 6, SYS_VECTOR, 0, mapvec3d, SYS_RES_A, (Vchar*)"", 0, {SYS_QUA_NONE, SYS_QUA_NONE}, 3, 0},
{(Vchar*)"Strainrate3D", 2, 0, 0, 6, SYS_TENSOR, 0, NULL, SYS_RES_E_RATE, (Vchar*)"", 0, {SYS_QUA_NONE, SYS_QUA_NONE}, 6, 0},
{(Vchar*)"Max_Equivalent_Stress",
 0,
 0,
 0,
 1,
 SYS_SCALAR,
 0,
 NULL,
 SYS_RES_S,
 (Vchar*)"",
 2,
 {SYS_QUA_MAXIMUM, SYS_QUA_EQUIV},
 1,
 0},
{(Vchar*)"Min_Equivalent_Stress",
 0,
 0,
 0,
 1,
 SYS_SCALAR,
 0,
 NULL,
 SYS_RES_S,
 (Vchar*)"",
 2,
 {SYS_QUA_MINIMUM, SYS_QUA_EQUIV},
 1,
 0},
{(Vchar*)"Membrane_Equivalent_Stress",
 0,
 0,
 PAM_ERF_MID,
 1,
 SYS_SCALAR,
 0,
 NULL,
 SYS_RES_S,
 (Vchar*)"",
 1,
 {SYS_QUA_EQUIV, SYS_QUA_NONE},
 1,
 0},
{(Vchar*)"Lower_S_Equivalent_Stress",
 0,
 0,
 PAM_ERF_BOT,
 1,
 SYS_SCALAR,
 0,
 NULL,
 SYS_RES_S,
 (Vchar*)"",
 1,
 {SYS_QUA_EQUIV, SYS_QUA_NONE},
 1,
 0},
{(Vchar*)"Upper_S_Equivalent_Stress",
 0,
 0,
 PAM_ERF_TOP,
 1,
 SYS_SCALAR,
 0,
 NULL,
 SYS_RES_S,
 (Vchar*)"",
 1,
 {SYS_QUA_EQUIV, SYS_QUA_NONE},
 1,
 0},
{(Vchar*)"Strain3D_Green_Lagrange",
 2,
 0,
 0,
 6,
 SYS_TENSOR,
 0,
 NULL,
 SYS_RES_E,
 (Vchar*)"",
 1,
 {SYS_QUA_GREEN, SYS_QUA_NONE},
 6,
 0},
{(Vchar*)"Strain3D", 2, 0, 0, 6, SYS_TENSOR, 0, NULL, SYS_RES_E, (Vchar*)"", 0, {SYS_QUA_NONE, SYS_QUA_NONE}, 6, 0},
{(Vchar*)"BEAM_Force", 1, -1, 0, 8, SYS_ELEMRES, 0, mapbf, SYS_RES_SFM, (Vchar*)"", 0, {SYS_QUA_NONE, SYS_QUA_NONE}, 3, 0},
{(Vchar*)"Upper_S_Stress",
 2,
 0,
 PAM_ERF_TOP,
 6,
 SYS_TENSOR,
 0,
 mapten2d,
 SYS_RES_S,
 (Vchar*)"",
 0,
 {SYS_QUA_NONE, SYS_QUA_NONE},
 3,
 0},
{(Vchar*)"Rotational_Angle_local",
 1,
 0,
 0,
 6,
 SYS_VECTOR,
 3,
 mapvec3d,
 SYS_RES_D,
 (Vchar*)"",
 1,
 {SYS_QUA_LOCAL, SYS_QUA_NONE},
 3,
 0},
{(Vchar*)"Rotational_Velocity_global",
 1,
 0,
 0,
 6,
 SYS_SIXDOF,
 3,
 mapvec3d,
 SYS_RES_V,
 (Vchar*)"",
 0,
 {SYS_QUA_NONE, SYS_QUA_NONE},
 3,
 0},
{(Vchar*)"Thermal_Flux", 1, 0, 0, 3, SYS_VECTOR, 0, NULL, SYS_RES_HEAT_FLUX, (Vchar*)"", 0, {SYS_QUA_NONE, SYS_QUA_NONE}, 3, 0},
{(Vchar*)"Displacement_global",
 1,
 0,
 0,
 6,
 SYS_VECTOR,
 0,
 mapvec3d,
 SYS_RES_D,
 (Vchar*)"",
 0,
 {SYS_QUA_NONE, SYS_QUA_NONE},
 3,
 0},
{(Vchar*)"Complex_Stress", 2, 0, 0, 6, SYS_TENSOR, 0, NULL, SYS_RES_S, (Vchar*)"", 0, {SYS_QUA_NONE, SYS_QUA_NONE}, 6, 0},
{(Vchar*)"Stress3D", 2, 0, 0, 6, SYS_TENSOR, 0, NULL, SYS_RES_S, (Vchar*)"", 0, {SYS_QUA_NONE, SYS_QUA_NONE}, 6, 0},
{(Vchar*)"Equivalent_Stress2D", 0, 0, 0, 1, SYS_SCALAR, 0, NULL, SYS_RES_S, (Vchar*)"", 1, {SYS_QUA_EQUIV, SYS_QUA_NONE}, 1, 0},
{(Vchar*)"Equivalent_Stress3D", 0, 0, 0, 1, SYS_SCALAR, 0, NULL, SYS_RES_S, (Vchar*)"", 1, {SYS_QUA_EQUIV, SYS_QUA_NONE}, 1, 0},
{(Vchar*)"Stress2D_Corner", 2, 0, 0, 6, SYS_TENSOR, 0, mapten2d, SYS_RES_S, (Vchar*)"", 0, {SYS_QUA_NONE, SYS_QUA_NONE}, 6, 0},
{(Vchar*)"Complex_Stress2D_Corner",
 2,
 0,
 0,
 6,
 SYS_TENSOR,
 0,
 mapten2d,
 SYS_RES_S,
 (Vchar*)"",
 0,
 {SYS_QUA_NONE, SYS_QUA_NONE},
 6,
 0},
{(Vchar*)"Stress3D_Corner", 2, 0, 0, 6, SYS_TENSOR, 0, NULL, SYS_RES_S, (Vchar*)"", 0, {SYS_QUA_NONE, SYS_QUA_NONE}, 6, 0},
{(Vchar*)"Complex_Stress3D_Corner",
 2,
 0,
 0,
 6,
 SYS_TENSOR,
 0,
 NULL,
 SYS_RES_S,
 (Vchar*)"",
 0,
 {SYS_QUA_NONE, SYS_QUA_NONE},
 6,
 0},
{(Vchar*)"Equivalent_Stress2D_Corner",
 0,
 0,
 0,
 1,
 SYS_SCALAR,
 0,
 NULL,
 SYS_RES_S,
 (Vchar*)"",
 1,
 {SYS_QUA_EQUIV, SYS_QUA_NONE},
 1,
 0},
{(Vchar*)"Upper_Thermal_Strain",
 0,
 0,
 PAM_ERF_TOP,
 1,
 SYS_SCALAR,
 0,
 NULL,
 SYS_RES_E,
 (Vchar*)"",
 1,
 {SYS_QUA_THERMAL, SYS_QUA_NONE},
 1,
 0},
{(Vchar*)"Lower_Thermal_Strain",
 0,
 0,
 PAM_ERF_BOT,
 1,
 SYS_SCALAR,
 0,
 NULL,
 SYS_RES_E,
 (Vchar*)"",
 1,
 {SYS_QUA_THERMAL, SYS_QUA_NONE},
 1,
 0},
{(Vchar*)"Moment_local", 0, 0, 0, 8, SYS_ELEMRES, 0, shellmom, SYS_RES_SFM, (Vchar*)"", 0, {SYS_QUA_NONE, SYS_QUA_NONE}, 3, 0},
{(Vchar*)"Rotational_Acceleration_local",
 1,
 0,
 0,
 6,
 SYS_VECTOR,
 3,
 mapvec3d,
 SYS_RES_A,
 (Vchar*)"",
 1,
 {SYS_QUA_LOCAL, SYS_QUA_NONE},
 3,
 0},
{(Vchar*)"Lower_Surface_Strain",
 2,
 0,
 PAM_ERF_BOT,
 6,
 SYS_TENSOR,
 0,
 NULL,
 SYS_RES_E,
 (Vchar*)"",
 0,
 {SYS_QUA_NONE, SYS_QUA_NONE},
 3,
 0},
{(Vchar*)"Lower_S_Strain",
 2,
 0,
 PAM_ERF_BOT,
 6,
 SYS_TENSOR,
 0,
 NULL,
 SYS_RES_E,
 (Vchar*)"",
 0,
 {SYS_QUA_NONE, SYS_QUA_NONE},
 3,
 0},
{(Vchar*)"Upper_S_Strain",
 2,
 0,
 PAM_ERF_TOP,
 6,
 SYS_TENSOR,
 0,
 NULL,
 SYS_RES_E,
 (Vchar*)"",
 0,
 {SYS_QUA_NONE, SYS_QUA_NONE},
 3,
 0},
{(Vchar*)"BAR_Axial_Force", 0, 0, 0, 8, SYS_ELEMRES, 0, barfor, SYS_RES_SFM, (Vchar*)"", 0, {SYS_QUA_NONE, SYS_QUA_NONE}, 1, 0},
{(Vchar*)"BEAM_Rotation_N1", 1, 1, 0, 8, SYS_ELEMRES, 0, mapbr, SYS_RES_SEK, (Vchar*)"", 0, {SYS_QUA_NONE, SYS_QUA_NONE}, 3, 0},
{(Vchar*)"BEAM_Rotation_N2", 1, 2, 0, 8, SYS_ELEMRES, 0, mapbr, SYS_RES_SEK, (Vchar*)"", 0, {SYS_QUA_NONE, SYS_QUA_NONE}, 3, 0},
{(Vchar*)"Rotational_Velocity_local",
 1,
 0,
 0,
 6,
 SYS_VECTOR,
 3,
 mapvec3d,
 SYS_RES_V,
 (Vchar*)"",
 1,
 {SYS_QUA_LOCAL, SYS_QUA_NONE},
 3,
 0},
{(Vchar*)"Rotational_Angle_global",
 1,
 0,
 0,
 6,
 SYS_VECTOR,
 3,
 mapvec3d,
 SYS_RES_D,
 (Vchar*)"",
 0,
 {SYS_QUA_NONE, SYS_QUA_NONE},
 3,
 0},
{(Vchar*)"Lower_Ply_Stress_XX",
 0,
 0,
 PAM_ERF_BOT,
 1,
 SYS_SCALAR,
 0,
 NULL,
 SYS_RES_S,
 (Vchar*)"PLY",
 1,
 {SYS_QUA_XX, SYS_QUA_NONE},
 1,
 0},
{(Vchar*)"Lower_Ply_Stress_YY",
 0,
 0,
 PAM_ERF_BOT,
 1,
 SYS_SCALAR,
 0,
 NULL,
 SYS_RES_S,
 (Vchar*)"PLY",
 1,
 {SYS_QUA_YY, SYS_QUA_NONE},
 1,
 0},
{(Vchar*)"Lower_Ply_Stress_XY",
 0,
 0,
 PAM_ERF_BOT,
 1,
 SYS_SCALAR,
 0,
 NULL,
 SYS_RES_S,
 (Vchar*)"PLY",
 1,
 {SYS_QUA_XY, SYS_QUA_NONE},
 1,
 0},
{(Vchar*)"Lower_Ply_Stress_XZ",
 0,
 0,
 PAM_ERF_BOT,
 1,
 SYS_SCALAR,
 0,
 NULL,
 SYS_RES_S,
 (Vchar*)"PLY",
 1,
 {SYS_QUA_ZX, SYS_QUA_NONE},
 1,
 0},
{(Vchar*)"Lower_Ply_Stress_YZ",
 0,
 0,
 PAM_ERF_BOT,
 1,
 SYS_SCALAR,
 0,
 NULL,
 SYS_RES_S,
 (Vchar*)"PLY",
 1,
 {SYS_QUA_YZ, SYS_QUA_NONE},
 1,
 0},
{(Vchar*)"Upper_Ply_Stress_XX",
 0,
 0,
 PAM_ERF_TOP,
 1,
 SYS_SCALAR,
 0,
 NULL,
 SYS_RES_S,
 (Vchar*)"PLY",
 1,
 {SYS_QUA_XX, SYS_QUA_NONE},
 1,
 0},
{(Vchar*)"Upper_Ply_Stress_YY",
 0,
 0,
 PAM_ERF_TOP,
 1,
 SYS_SCALAR,
 0,
 NULL,
 SYS_RES_S,
 (Vchar*)"PLY",
 1,
 {SYS_QUA_YY, SYS_QUA_NONE},
 1,
 0},
{(Vchar*)"Upper_Ply_Stress_XY",
 0,
 0,
 PAM_ERF_TOP,
 1,
 SYS_SCALAR,
 0,
 NULL,
 SYS_RES_S,
 (Vchar*)"PLY",
 1,
 {SYS_QUA_XY, SYS_QUA_NONE},
 1,
 0},
{(Vchar*)"Upper_Ply_Stress_XZ",
 0,
 0,
 PAM_ERF_TOP,
 1,
 SYS_SCALAR,
 0,
 NULL,
 SYS_RES_S,
 (Vchar*)"PLY",
 1,
 {SYS_QUA_ZX, SYS_QUA_NONE},
 1,
 0},
{(Vchar*)"Upper_Ply_Stress_YZ",
 0,
 0,
 PAM_ERF_TOP,
 1,
 SYS_SCALAR,
 0,
 NULL,
 SYS_RES_S,
 (Vchar*)"PLY",
 1,
 {SYS_QUA_YZ, SYS_QUA_NONE},
 1,
 0},
{(Vchar*)"Translational_Acceleration_local",
 1,
 0,
 0,
 6,
 SYS_VECTOR,
 0,
 mapvec3d,
 SYS_RES_A,
 (Vchar*)"",
 1,
 {SYS_QUA_LOCAL, SYS_QUA_NONE},
 3,
 0},
{(Vchar*)"BEAM_Moment_N1", 1, 1, 0, 8, SYS_ELEMRES, 0, mapbm, SYS_RES_SFM, (Vchar*)"", 0, {SYS_QUA_NONE, SYS_QUA_NONE}, 3, 0},
{(Vchar*)"BEAM_Moment_N2", 1, 2, 0, 8, SYS_ELEMRES, 0, mapbm, SYS_RES_SFM, (Vchar*)"", 0, {SYS_QUA_NONE, SYS_QUA_NONE}, 3, 0},
{(Vchar*)"Upper_Surface_Strain",
 2,
 0,
 PAM_ERF_TOP,
 6,
 SYS_TENSOR,
 0,
 NULL,
 SYS_RES_E,
 (Vchar*)"",
 0,
 {SYS_QUA_NONE, SYS_QUA_NONE},
 3,
 0},
{(Vchar*)"Thickness", 0, 0, 0, 1, SYS_SCALAR, 0, NULL, SYS_RES_THICKNESS, (Vchar*)"", 0, {SYS_QUA_NONE, SYS_QUA_NONE}, 1, 0},
{(Vchar*)"BAR_Axial_Strain", 0, 0, 0, 8, SYS_ELEMRES, 0, barfor, SYS_RES_SEK, (Vchar*)"", 0, {SYS_QUA_NONE, SYS_QUA_NONE}, 1, 0},
{(Vchar*)"Translational_Velocity_local",
 1,
 0,
 0,
 6,
 SYS_VECTOR,
 0,
 mapvec3d,
 SYS_RES_V,
 (Vchar*)"",
 1,
 {SYS_QUA_LOCAL, SYS_QUA_NONE},
 3,
 0},
{(Vchar*)"COORDINATE", 1, 0, 0, 3, SYS_VECTOR, 0, NULL, SYS_RES_X, (Vchar*)"", 0, {SYS_QUA_NONE, SYS_QUA_NONE}, 3, 0},
{(Vchar*)"Contact_Pressure_X",
 0,
 0,
 0,
 3,
 SYS_VECTOR,
 0,
 NULL,
 SYS_RES_TRAC,
 (Vchar*)"",
 1,
 {SYS_QUA_CONTACT, SYS_QUA_NONE},
 1,
 0},
{(Vchar*)"Contact_Pressure_Y",
 0,
 0,
 0,
 3,
 SYS_VECTOR,
 1,
 NULL,
 SYS_RES_TRAC,
 (Vchar*)"",
 1,
 {SYS_QUA_CONTACT, SYS_QUA_NONE},
 1,
 0},
{(Vchar*)"Contact_Pressure_Z",
 0,
 0,
 0,
 3,
 SYS_VECTOR,
 2,
 NULL,
 SYS_RES_TRAC,
 (Vchar*)"",
 1,
 {SYS_QUA_CONTACT, SYS_QUA_NONE},
 1,
 0},
{(Vchar*)"Contact_Pressure_N",
 0,
 0,
 0,
 1,
 SYS_SCALAR,
 0,
 NULL,
 SYS_RES_PRES,
 (Vchar*)"",
 1,
 {SYS_QUA_CONTACT, SYS_QUA_NONE},
 1,
 0},
{(Vchar*)"Contact_Force", 1, 0, 0, 3, SYS_VECTOR, 0, NULL, SYS_RES_FORCE, (Vchar*)"", 1, {SYS_QUA_CONTACT, SYS_QUA_NONE}, 3, 0},
{(Vchar*)"Membrane_Stress_Res_local",
 0,
 0,
 0,
 8,
 SYS_ELEMRES,
 0,
 shellfor,
 SYS_RES_SFM,
 (Vchar*)"",
 0,
 {SYS_QUA_NONE, SYS_QUA_NONE},
 3,
 0},
{(Vchar*)"Rotational_Acceleration_global",
 1,
 0,
 0,
 6,
 SYS_VECTOR,
 3,
 mapvec3d,
 SYS_RES_A,
 (Vchar*)"",
 0,
 {SYS_QUA_NONE, SYS_QUA_NONE},
 3,
 0},
{(Vchar*)"BEAM_Elongation", 0, -1, 0, 8, SYS_ELEMRES, 0, NULL, SYS_RES_SEK, (Vchar*)"", 0, {SYS_QUA_NONE, SYS_QUA_NONE}, 1, 0},
{(Vchar*)"Lower_S_Stress",
 2,
 0,
 PAM_ERF_BOT,
 6,
 SYS_TENSOR,
 0,
 mapten2d,
 SYS_RES_S,
 (Vchar*)"",
 0,
 {SYS_QUA_NONE, SYS_QUA_NONE},
 3,
 0},
{(Vchar*)"Lower_Ply_Strain_XX",
 0,
 0,
 PAM_ERF_BOT,
 1,
 SYS_SCALAR,
 0,
 NULL,
 SYS_RES_E,
 (Vchar*)"PLY",
 1,
 {SYS_QUA_XX, SYS_QUA_NONE},
 1,
 0},
{(Vchar*)"Lower_Ply_Strain_YY",
 0,
 0,
 PAM_ERF_BOT,
 1,
 SYS_SCALAR,
 0,
 NULL,
 SYS_RES_E,
 (Vchar*)"PLY",
 1,
 {SYS_QUA_YY, SYS_QUA_NONE},
 1,
 0},
{(Vchar*)"Lower_Ply_Strain_XY",
 0,
 0,
 PAM_ERF_BOT,
 1,
 SYS_SCALAR,
 0,
 NULL,
 SYS_RES_E,
 (Vchar*)"PLY",
 1,
 {SYS_QUA_XY, SYS_QUA_NONE},
 1,
 0},
{(Vchar*)"Lower_Ply_Strain_XZ",
 0,
 0,
 PAM_ERF_BOT,
 1,
 SYS_SCALAR,
 0,
 NULL,
 SYS_RES_E,
 (Vchar*)"PLY",
 1,
 {SYS_QUA_ZX, SYS_QUA_NONE},
 1,
 0},
{(Vchar*)"Lower_Ply_Strain_YZ",
 0,
 0,
 PAM_ERF_BOT,
 1,
 SYS_SCALAR,
 0,
 NULL,
 SYS_RES_E,
 (Vchar*)"PLY",
 1,
 {SYS_QUA_YZ, SYS_QUA_NONE},
 1,
 0},
{(Vchar*)"Upper_Ply_Strain_XX",
 0,
 0,
 PAM_ERF_TOP,
 1,
 SYS_SCALAR,
 0,
 NULL,
 SYS_RES_E,
 (Vchar*)"PLY",
 1,
 {SYS_QUA_XX, SYS_QUA_NONE},
 1,
 0},
{(Vchar*)"Upper_Ply_Strain_YY",
 0,
 0,
 PAM_ERF_TOP,
 1,
 SYS_SCALAR,
 0,
 NULL,
 SYS_RES_E,
 (Vchar*)"PLY",
 1,
 {SYS_QUA_YY, SYS_QUA_NONE},
 1,
 0},
{(Vchar*)"Upper_Ply_Strain_XY",
 0,
 0,
 PAM_ERF_TOP,
 1,
 SYS_SCALAR,
 0,
 NULL,
 SYS_RES_E,
 (Vchar*)"PLY",
 1,
 {SYS_QUA_XY, SYS_QUA_NONE},
 1,
 0},
{(Vchar*)"Upper_Ply_Strain_XZ",
 0,
 0,
 PAM_ERF_TOP,
 1,
 SYS_SCALAR,
 0,
 NULL,
 SYS_RES_E,
 (Vchar*)"PLY",
 1,
 {SYS_QUA_ZX, SYS_QUA_NONE},
 1,
 0},
{(Vchar*)"Upper_Ply_Strain_YZ",
 0,
 0,
 PAM_ERF_TOP,
 1,
 SYS_SCALAR,
 0,
 NULL,
 SYS_RES_E,
 (Vchar*)"PLY",
 1,
 {SYS_QUA_YZ, SYS_QUA_NONE},
 1,
 0},
{(Vchar*)"Lower_Ply_Tsai_Wu_Criterion",
 0,
 0,
 PAM_ERF_BOT,
 1,
 SYS_SCALAR,
 0,
 NULL,
 SYS_RES_FAT_DAMAGE,
 (Vchar*)"PLY,TSAI_WU",
 0,
 {SYS_QUA_NONE, SYS_QUA_NONE},
 1,
 0},
{(Vchar*)"Upper_Ply_Tsai_Wu_Criterion",
 0,
 0,
 PAM_ERF_TOP,
 1,
 SYS_SCALAR,
 0,
 NULL,
 SYS_RES_FAT_DAMAGE,
 (Vchar*)"PLY,TSAI_WU",
 0,
 {SYS_QUA_NONE, SYS_QUA_NONE},
 1,
 0},
{(Vchar*)"Max_Plastic_Strain", 0, 0, 0, 1, SYS_SCALAR, 0, NULL, SYS_RES_E, (Vchar*)"", 2, {SYS_QUA_MAXIMUM, SYS_QUA_PLAST}, 1, 0},
{(Vchar*)"Min_Plastic_Strain", 0, 0, 0, 1, SYS_SCALAR, 0, NULL, SYS_RES_E, (Vchar*)"", 2, {SYS_QUA_MINIMUM, SYS_QUA_PLAST}, 1, 0},
{(Vchar*)"Membrane_Plastic_Strain",
 0,
 0,
 0,
 1,
 SYS_SCALAR,
 0,
 NULL,
 SYS_RES_E,
 (Vchar*)"",
 2,
 {SYS_QUA_EQUIV, SYS_QUA_PLAST},
 1,
 0},
{(Vchar*)"FPM_Static_Density",
 0,
 0,
 0,
 1,
 SYS_SCALAR,
 0,
 NULL,
 SYS_RES_DENS,
 (Vchar*)"FPM",
 1,
 {SYS_QUA_STATIC, SYS_QUA_NONE},
 1,
 0},
{(Vchar*)"FPM_Static_Temperature",
 0,
 0,
 0,
 1,
 SYS_SCALAR,
 0,
 NULL,
 SYS_RES_TEMP,
 (Vchar*)"FPM",
 1,
 {SYS_QUA_STATIC, SYS_QUA_NONE},
 1,
 0},
{(Vchar*)"FPM_Static_Pressure",
 0,
 0,
 0,
 1,
 SYS_SCALAR,
 0,
 NULL,
 SYS_RES_PRES,
 (Vchar*)"FPM",
 1,
 {SYS_QUA_STATIC, SYS_QUA_NONE},
 1,
 0},
{(Vchar*)"OTMCO Reaction force",
 0,
 0,
 0,
 6,
 SYS_VECTOR,
 0,
 mapvec3d,
 SYS_RES_R,
 (Vchar*)"",
 1,
 {SYS_QUA_MPC, SYS_QUA_NONE},
 1,
 0},
{(Vchar*)"OTMCO Reaction moment",
 0,
 0,
 0,
 6,
 SYS_VECTOR,
 3,
 mapvec3d,
 SYS_RES_R,
 (Vchar*)"",
 0,
 {SYS_QUA_MPC, SYS_QUA_NONE},
 1,
 0},
{(Vchar*)"BASIS3X3", 0, 0, 0, 3, SYS_VECTOR, 0, NULL, SYS_RES_ROT_ANG, (Vchar*)"", 0, {SYS_QUA_NONE, SYS_QUA_NONE}, 1, 0},
{(Vchar*)"TEMP", 0, 0, 0, 1, SYS_SCALAR, 0, NULL, SYS_RES_TEMP, (Vchar*)"", 0, {SYS_QUA_NONE, SYS_QUA_NONE}, 1, 0},
{(Vchar*)"BEAM_Stress_P1",
 0,
 0,
 PAM_ERF_BEAM1,
 6,
 SYS_TENSOR,
 0,
 NULL,
 SYS_RES_S,
 (Vchar*)"",
 0,
 {SYS_QUA_NONE, SYS_QUA_NONE},
 1,
 0},
{(Vchar*)"BEAM_Stress_P2",
 0,
 0,
 PAM_ERF_BEAM2,
 6,
 SYS_TENSOR,
 0,
 NULL,
 SYS_RES_S,
 (Vchar*)"",
 0,
 {SYS_QUA_NONE, SYS_QUA_NONE},
 1,
 0},
{(Vchar*)"BEAM_Stress_P3",
 0,
 0,
 PAM_ERF_BEAM3,
 6,
 SYS_TENSOR,
 0,
 NULL,
 SYS_RES_S,
 (Vchar*)"",
 0,
 {SYS_QUA_NONE, SYS_QUA_NONE},
 1,
 0},
{(Vchar*)"BEAM_Stress_P4",
 0,
 0,
 PAM_ERF_BEAM4,
 6,
 SYS_TENSOR,
 0,
 NULL,
 SYS_RES_S,
 (Vchar*)"",
 0,
 {SYS_QUA_NONE, SYS_QUA_NONE},
 1,
 0},
{(Vchar*)"RFLUX", 0, 0, 0, 1, SYS_SCALAR, 0, NULL, SYS_RES_R_HEAT_FLOW, (Vchar*)"", 0, {SYS_QUA_NONE, SYS_QUA_NONE}, 1, 0},
{(Vchar*)"DMG", 0, 0, 0, 1, SYS_SCALAR, 0, NULL, SYS_RES_FAT_DAMAGE, (Vchar*)"", 0, {SYS_QUA_NONE, SYS_QUA_NONE}, 1, 0},
{(Vchar*)"DINT", 0, 0, 0, 1, SYS_SCALAR, 0, NULL, SYS_RES_ENERGY_DENSITY, (Vchar*)"", 0, {SYS_QUA_NONE, SYS_QUA_NONE}, 1, 0},
{(Vchar*)"DHGL",
 0,
 0,
 0,
 1,
 SYS_SCALAR,
 0,
 NULL,
 SYS_RES_ENERGY_DENSITY,
 (Vchar*)"HOURGLASS",
 0,
 {SYS_QUA_NONE, SYS_QUA_NONE},
 1,
 0},
{(Vchar*)"EINT", 0, 0, 0, 1, SYS_SCALAR, 0, NULL, SYS_RES_ENERGY, (Vchar*)"", 0, {SYS_QUA_NONE, SYS_QUA_NONE}, 1, 0},
{(Vchar*)"EHGL", 0, 0, 0, 1, SYS_SCALAR, 0, NULL, SYS_RES_ENERGY, (Vchar*)"HOURGLASS", 0, {SYS_QUA_NONE, SYS_QUA_NONE}, 1, 0},
{(Vchar*)"Translation X", 0, 0, 0, 1, SYS_SCALAR, 0, NULL, SYS_RES_D, (Vchar*)"", 1, {SYS_QUA_TX, SYS_QUA_NONE}, 1, 0},
{(Vchar*)"Translation Y", 0, 0, 0, 1, SYS_SCALAR, 0, NULL, SYS_RES_D, (Vchar*)"", 1, {SYS_QUA_TY, SYS_QUA_NONE}, 1, 0},
{(Vchar*)"Translation Z", 0, 0, 0, 1, SYS_SCALAR, 0, NULL, SYS_RES_D, (Vchar*)"", 1, {SYS_QUA_TZ, SYS_QUA_NONE}, 1, 0},
{(Vchar*)"Rotation X", 0, 0, 0, 1, SYS_SCALAR, 0, NULL, SYS_RES_D, (Vchar*)"", 1, {SYS_QUA_RX, SYS_QUA_NONE}, 1, 0},
{(Vchar*)"Rotation Y", 0, 0, 0, 1, SYS_SCALAR, 0, NULL, SYS_RES_D, (Vchar*)"", 1, {SYS_QUA_RY, SYS_QUA_NONE}, 1, 0},
{(Vchar*)"Rotation Z", 0, 0, 0, 1, SYS_SCALAR, 0, NULL, SYS_RES_D, (Vchar*)"", 1, {SYS_QUA_RZ, SYS_QUA_NONE}, 1, 0},
{(Vchar*)"FrameMatrix", 2, 0, 0, 3, SYS_VECTOR, 0, NULL, SYS_RES_ROT_ANG, (Vchar*)"", 0, {SYS_QUA_NONE, SYS_QUA_NONE}, 9, 3},
{(Vchar*)"Lower_Engineering_Strain",
 2,
 0,
 PAM_ERF_BOT,
 6,
 SYS_TENSOR,
 0,
 NULL,
 SYS_RES_E,
 (Vchar*)"",
 1,
 {SYS_QUA_ENG, SYS_QUA_NONE},
 6,
 0},
{(Vchar*)"Upper_Engineering_Strain",
 2,
 0,
 PAM_ERF_TOP,
 6,
 SYS_TENSOR,
 0,
 NULL,
 SYS_RES_E,
 (Vchar*)"",
 1,
 {SYS_QUA_ENG, SYS_QUA_NONE},
 6,
 0},
{(Vchar*)"Lower_Strain", 2, 0, PAM_ERF_BOT, 6, SYS_TENSOR, 0, NULL, SYS_RES_E, (Vchar*)"", 0, {SYS_QUA_NONE, SYS_QUA_NONE}, 6, 0},
{(Vchar*)"Upper_Strain", 2, 0, PAM_ERF_TOP, 6, SYS_TENSOR, 0, NULL, SYS_RES_E, (Vchar*)"", 0, {SYS_QUA_NONE, SYS_QUA_NONE}, 6, 0},
{(Vchar*)"Lower_Stress",
 2,
 0,
 PAM_ERF_BOT,
 6,
 SYS_TENSOR,
 0,
 mapten2d,
 SYS_RES_S,
 (Vchar*)"",
 0,
 {SYS_QUA_NONE, SYS_QUA_NONE},
 9,
 0},
{(Vchar*)"Upper_Stress",
 2,
 0,
 PAM_ERF_TOP,
 6,
 SYS_TENSOR,
 0,
 mapten2d,
 SYS_RES_S,
 (Vchar*)"",
 0,
 {SYS_QUA_NONE, SYS_QUA_NONE},
 9,
 0},
{(Vchar*)"Complex_Lower_Stress",
 2,
 0,
 PAM_ERF_BOT,
 6,
 SYS_TENSOR,
 0,
 mapten2d,
 SYS_RES_S,
 (Vchar*)"",
 0,
 {SYS_QUA_NONE, SYS_QUA_NONE},
 9,
 0},
{(Vchar*)"Complex_Upper_Stress",
 2,
 0,
 PAM_ERF_TOP,
 6,
 SYS_TENSOR,
 0,
 mapten2d,
 SYS_RES_S,
 (Vchar*)"",
 0,
 {SYS_QUA_NONE, SYS_QUA_NONE},
 9,
 0},
{(Vchar*)"Lower_Backstress",
 2,
 0,
 PAM_ERF_BOT,
 6,
 SYS_TENSOR,
 0,
 NULL,
 SYS_RES_S,
 (Vchar*)"BACK",
 0,
 {SYS_QUA_NONE, SYS_QUA_NONE},
 3,
 0},
{(Vchar*)"Membrane_Backstress",
 2,
 0,
 PAM_ERF_MID,
 6,
 SYS_TENSOR,
 0,
 NULL,
 SYS_RES_S,
 (Vchar*)"BACK",
 0,
 {SYS_QUA_NONE, SYS_QUA_NONE},
 3,
 0},
{(Vchar*)"Upper_Backstress",
 2,
 0,
 PAM_ERF_TOP,
 6,
 SYS_TENSOR,
 0,
 NULL,
 SYS_RES_S,
 (Vchar*)"BACK",
 0,
 {SYS_QUA_NONE, SYS_QUA_NONE},
 3,
 0},
{(Vchar*)"CRMS_Pressure", 0, 0, 0, 1, SYS_SCALAR, 0, NULL, SYS_RES_PRES, (Vchar*)"CRMS", 0, {SYS_QUA_NONE, SYS_QUA_NONE}, 1, 0},
{(Vchar*)"CRMS_Displacement", 1, 0, 0, 6, SYS_SIXDOF, 0, NULL, SYS_RES_D, (Vchar*)"CRMS", 0, {SYS_QUA_NONE, SYS_QUA_NONE}, 3, 0},
{(Vchar*)"Translational_Displacement_Local",
 1,
 0,
 0,
 6,
 SYS_SIXDOF,
 0,
 NULL,
 SYS_RES_D,
 (Vchar*)"[LOCAL]",
 0,
 {SYS_QUA_NONE, SYS_QUA_NONE},
 3,
 0},
{(Vchar*)"Reaction Moment", 1, 0, 0, 6, SYS_SIXDOF, 3, NULL, SYS_RES_R, (Vchar*)"", 0, {SYS_QUA_NONE, SYS_QUA_NONE}, 6, 0},
{(Vchar*)"Frictional_Energy",
 0,
 0,
 0,
 1,
 SYS_SCALAR,
 0,
 NULL,
 SYS_RES_ENERGY,
 (Vchar*)"",
 1,
 {SYS_QUA_FRICTION, SYS_QUA_NONE},
 3,
 0},
{(Vchar*)"Axial_Strain", 0, 0, 0, 8, SYS_ELEMRES, 0, NULL, SYS_RES_SEK, (Vchar*)"", 0, {SYS_QUA_NONE, SYS_QUA_NONE}, 1, 0},
{(Vchar*)"Elastic_Energy", 0, 0, 0, 1, SYS_SCALAR, 0, NULL, SYS_RES_ENERGY, (Vchar*)"", 1, {SYS_QUA_ELAST, SYS_QUA_NONE}, 3, 0},
{(Vchar*)"FPM_Mach_Number", 0, 0, 0, 1, SYS_SCALAR, 0, NULL, SYS_RES_MACH, (Vchar*)"FPM", 0, {SYS_QUA_NONE, SYS_QUA_NONE}, 1, 0},
{(Vchar*)"MUSCLE_Velocity", 0, 0, 0, 1, SYS_SCALAR, 0, NULL, SYS_RES_V, (Vchar*)"MUSCLE", 0, {SYS_QUA_NONE, SYS_QUA_NONE}, 13, 0},
{(Vchar*)"Average_Nodal_Velocity",
 1,
 0,
 0,
 3,
 SYS_VECTOR,
 0,
 NULL,
 SYS_RES_V,
 (Vchar*)"AVERAGE",
 0,
 {SYS_QUA_NONE, SYS_QUA_NONE},
 3,
 0},
{(Vchar*)"Translational_Acceleration_Local",
 1,
 0,
 0,
 6,
 SYS_SIXDOF,
 0,
 NULL,
 SYS_RES_A,
 (Vchar*)"",
 0,
 {SYS_QUA_NONE, SYS_QUA_NONE},
 3,
 0},
{(Vchar*)"Chamber_Pressure",
 0,
 0,
 0,
 1,
 SYS_SCALAR,
 0,
 NULL,
 SYS_RES_PRES,
 (Vchar*)"CHAMBER",
 0,
 {SYS_QUA_NONE, SYS_QUA_NONE},
 9,
 0},
{(Vchar*)"COR_Displacement", 1, 0, 0, 6, SYS_SIXDOF, 0, NULL, SYS_RES_D, (Vchar*)"COR", 0, {SYS_QUA_NONE, SYS_QUA_NONE}, 3, 0},
{(Vchar*)"FPM_Total_Density",
 0,
 0,
 0,
 1,
 SYS_SCALAR,
 0,
 NULL,
 SYS_RES_DENS,
 (Vchar*)"FPM",
 0,
 {SYS_QUA_NONE, SYS_QUA_NONE},
 1,
 0},
{(Vchar*)"Principal_Stress", 1, 0, 0, 3, SYS_VECTOR, 0, NULL, SYS_RES_S, (Vchar*)"", 1, {SYS_QUA_PRINCIPAL, SYS_QUA_NONE}, 3, 0},
{(Vchar*)"CRMS_Acceleration", 1, 0, 0, 6, SYS_SIXDOF, 0, NULL, SYS_RES_A, (Vchar*)"CRMS", 0, {SYS_QUA_NONE, SYS_QUA_NONE}, 3, 0},
{(Vchar*)"Acoustic_Pressure",
 0,
 0,
 0,
 1,
 SYS_SCALAR,
 0,
 NULL,
 SYS_RES_PRES,
 (Vchar*)"ACOUSTIC",
 0,
 {SYS_QUA_NONE, SYS_QUA_NONE},
 1,
 0},
{(Vchar*)"Top_Plastic_Strain",
 0,
 0,
 PAM_ERF_TOP,
 1,
 SYS_SCALAR,
 0,
 NULL,
 SYS_RES_E,
 (Vchar*)"",
 1,
 {SYS_QUA_PLAST, SYS_QUA_NONE},
 1,
 0},
{(Vchar*)"Chamber_Volume",
 0,
 0,
 0,
 1,
 SYS_SCALAR,
 0,
 NULL,
 SYS_RES_VOLUME,
 (Vchar*)"CHAMBER",
 0,
 {SYS_QUA_NONE, SYS_QUA_NONE},
 9,
 0},
{(Vchar*)"CRMS_Velocity", 1, 0, 0, 6, SYS_SIXDOF, 0, NULL, SYS_RES_V, (Vchar*)"CRMS", 0, {SYS_QUA_NONE, SYS_QUA_NONE}, 3, 0},
{(Vchar*)"SPH_Volume", 0, 0, 0, 1, SYS_SCALAR, 0, NULL, SYS_RES_VOLUME, (Vchar*)"SPH", 0, {SYS_QUA_NONE, SYS_QUA_NONE}, 3, 0},
{(Vchar*)"Rotational_Velocity", 1, 0, 0, 6, SYS_SIXDOF, 3, NULL, SYS_RES_V, (Vchar*)"", 0, {SYS_QUA_NONE, SYS_QUA_NONE}, 3, 0},
{(Vchar*)"Translational_Displacement",
 1,
 0,
 0,
 6,
 SYS_SIXDOF,
 0,
 NULL,
 SYS_RES_D,
 (Vchar*)"",
 0,
 {SYS_QUA_NONE, SYS_QUA_NONE},
 3,
 0},
{(Vchar*)"Axial_Force", 0, 0, 0, 8, SYS_ELEMRES, 0, NULL, SYS_RES_SFM, (Vchar*)"", 0, {SYS_QUA_NONE, SYS_QUA_NONE}, 1, 0},
{(Vchar*)"COR_Acceleration", 1, 0, 0, 6, SYS_SIXDOF, 0, NULL, SYS_RES_A, (Vchar*)"COR", 0, {SYS_QUA_NONE, SYS_QUA_NONE}, 3, 0},
{(Vchar*)"Strain_tensor", 2, 0, 0, 6, SYS_TENSOR, 0, NULL, SYS_RES_E, (Vchar*)"", 0, {SYS_QUA_NONE, SYS_QUA_NONE}, 6, 0},
{(Vchar*)"PSD_Pressure", 0, 0, 0, 1, SYS_SCALAR, 0, NULL, SYS_RES_PRES, (Vchar*)"", 1, {SYS_QUA_PSD, SYS_QUA_NONE}, 1, 0},
{(Vchar*)"Contact_Energy", 0, 0, 0, 1, SYS_SCALAR, 0, NULL, SYS_RES_ENERGY, (Vchar*)"", 1, {SYS_QUA_CONTACT, SYS_QUA_NONE}, 2, 0},
{(Vchar*)"COR_Displacement_Local",
 1,
 0,
 0,
 6,
 SYS_SIXDOF,
 0,
 NULL,
 SYS_RES_D,
 (Vchar*)"COR",
 0,
 {SYS_QUA_NONE, SYS_QUA_NONE},
 3,
 0},
{(Vchar*)"Shell_Membrane_Energy",
 0,
 0,
 PAM_ERF_MID,
 1,
 SYS_SCALAR,
 0,
 NULL,
 SYS_RES_ENERGY,
 (Vchar*)"",
 0,
 {SYS_QUA_NONE, SYS_QUA_NONE},
 3,
 0},
{(Vchar*)"Rotational_Displacement",
 1,
 0,
 0,
 6,
 SYS_SIXDOF,
 3,
 NULL,
 SYS_RES_D,
 (Vchar*)"",
 0,
 {SYS_QUA_NONE, SYS_QUA_NONE},
 3,
 0},
{(Vchar*)"Reaction Force", 1, 0, 0, 6, SYS_SIXDOF, 0, NULL, SYS_RES_R, (Vchar*)"", 0, {SYS_QUA_NONE, SYS_QUA_NONE}, 6, 0},
{(Vchar*)"Airbag_Pressure",
 0,
 0,
 0,
 1,
 SYS_SCALAR,
 0,
 NULL,
 SYS_RES_PRES,
 (Vchar*)"AIRBAG",
 0,
 {SYS_QUA_NONE, SYS_QUA_NONE},
 7,
 0},
{(Vchar*)"TIME", 0, 0, 0, 1, SYS_SCALAR, 0, NULL, SYS_RES_TIME, (Vchar*)"", 0, {SYS_QUA_NONE, SYS_QUA_NONE}, 1, 0},
{(Vchar*)"Equivalent_Strain_Rate",
 0,
 0,
 0,
 1,
 SYS_SCALAR,
 0,
 NULL,
 SYS_RES_E_RATE,
 (Vchar*)"",
 1,
 {SYS_QUA_EQUIV, SYS_QUA_NONE},
 1,
 0},
{(Vchar*)"Porosity", 0, 0, 0, 1, SYS_SCALAR, 0, NULL, SYS_RES_POROSITY, (Vchar*)"", 0, {SYS_QUA_NONE, SYS_QUA_NONE}, 1, 0},
{(Vchar*)"Complex_Translational_Acceleration",
 1,
 0,
 0,
 6,
 SYS_SIXDOF,
 0,
 NULL,
 SYS_RES_A,
 (Vchar*)"",
 0,
 {SYS_QUA_NONE, SYS_QUA_NONE},
 3,
 0},
{(Vchar*)"Translational_Acceleration",
 1,
 0,
 0,
 6,
 SYS_SIXDOF,
 0,
 NULL,
 SYS_RES_A,
 (Vchar*)"",
 0,
 {SYS_QUA_NONE, SYS_QUA_NONE},
 3,
 0},
{(Vchar*)"COR_Acceleration_Local",
 1,
 0,
 0,
 6,
 SYS_SIXDOF,
 0,
 NULL,
 SYS_RES_A,
 (Vchar*)"COR",
 0,
 {SYS_QUA_NONE, SYS_QUA_NONE},
 3,
 0},
{(Vchar*)"Internal_Energy",
 0,
 0,
 0,
 1,
 SYS_SCALAR,
 0,
 NULL,
 SYS_RES_ENERGY,
 (Vchar*)"",
 1,
 {SYS_QUA_INTERNAL, SYS_QUA_NONE},
 1,
 0},
{(Vchar*)"Complex_Internal_Energy_Mean",
 0,
 0,
 0,
 1,
 SYS_SCALAR,
 0,
 NULL,
 SYS_RES_ENERGY,
 (Vchar*)"",
 2,
 {SYS_QUA_INTERNAL, SYS_QUA_MEAN},
 1,
 0},
{(Vchar*)"COR_Pressure", 0, 0, 0, 1, SYS_SCALAR, 0, NULL, SYS_RES_PRES, (Vchar*)"COR", 0, {SYS_QUA_NONE, SYS_QUA_NONE}, 1, 0},
{(Vchar*)"Porous_Pressure", 0, 0, 0, 1, SYS_SCALAR, 0, NULL, SYS_RES_PRES, (Vchar*)"", 1, {SYS_QUA_PORE, SYS_QUA_NONE}, 1, 0},
{(Vchar*)"CRMS_Displacement_Local",
 1,
 0,
 0,
 6,
 SYS_SIXDOF,
 0,
 NULL,
 SYS_RES_D,
 (Vchar*)"CRMS",
 0,
 {SYS_QUA_NONE, SYS_QUA_NONE},
 3,
 0},
{(Vchar*)"Rotational_Acceleration",
 1,
 0,
 0,
 6,
 SYS_SIXDOF,
 3,
 NULL,
 SYS_RES_A,
 (Vchar*)"",
 0,
 {SYS_QUA_NONE, SYS_QUA_NONE},
 3,
 0},
{(Vchar*)"Moment", -2, 0, 0, 6, SYS_SIXDOF, 3, NULL, SYS_RES_EN_FORC, (Vchar*)"", 0, {SYS_QUA_NONE, SYS_QUA_NONE}, 3, 0},
{(Vchar*)"CRMS_Acceleration_Local",
 1,
 0,
 0,
 6,
 SYS_SIXDOF,
 0,
 NULL,
 SYS_RES_A,
 (Vchar*)"CRMS",
 0,
 {SYS_QUA_NONE, SYS_QUA_NONE},
 3,
 0},
{(Vchar*)"COR_Velocity_Local", 1, 0, 0, 6, SYS_SIXDOF, 0, NULL, SYS_RES_V, (Vchar*)"COR", 0, {SYS_QUA_NONE, SYS_QUA_NONE}, 3, 0},
{(Vchar*)"Max_Total_Equivalent_Strain",
 0,
 0,
 0,
 1,
 SYS_SCALAR,
 0,
 NULL,
 SYS_RES_E,
 (Vchar*)"",
 2,
 {SYS_QUA_MAXIMUM, SYS_QUA_EQUIV},
 1,
 0},
{(Vchar*)"Torsion_Angle", 0, -1, 0, 8, SYS_ELEMRES, 3, NULL, SYS_RES_SEK, (Vchar*)"", 0, {SYS_QUA_NONE, SYS_QUA_NONE}, 1, 0},
{(Vchar*)"Axial_Elongation", 0, -1, 0, 8, SYS_ELEMRES, 0, NULL, SYS_RES_SEK, (Vchar*)"", 0, {SYS_QUA_NONE, SYS_QUA_NONE}, 1, 0},
{(Vchar*)"Min_Creep_Strain", 0, 0, 0, 1, SYS_SCALAR, 0, NULL, SYS_RES_E, (Vchar*)"", 2, {SYS_QUA_MINIMUM, SYS_QUA_CREEP}, 1, 0},
{(Vchar*)"Airbag_Volume",
 0,
 0,
 0,
 1,
 SYS_SCALAR,
 0,
 NULL,
 SYS_RES_VOLUME,
 (Vchar*)"AIRBAR",
 0,
 {SYS_QUA_NONE, SYS_QUA_NONE},
 7,
 0},
{(Vchar*)"FPM_Sound_Speed", 0, 0, 0, 1, SYS_SCALAR, 0, NULL, SYS_RES_V, (Vchar*)"FPM", 0, {SYS_QUA_SOUND, SYS_QUA_NONE}, 1, 0},
{(Vchar*)"Principal_Strain_Rate",
 1,
 0,
 0,
 3,
 SYS_VECTOR,
 0,
 NULL,
 SYS_RES_E_RATE,
 (Vchar*)"",
 1,
 {SYS_QUA_PRINCIPAL, SYS_QUA_NONE},
 3,
 0},
{(Vchar*)"PSD_Velocity_Local", 1, 0, 0, 6, SYS_SIXDOF, 0, NULL, SYS_RES_V, (Vchar*)"", 1, {SYS_QUA_PSD, SYS_QUA_NONE}, 3, 0},
{(Vchar*)"Damping_Energy",
 0,
 0,
 0,
 1,
 SYS_SCALAR,
 0,
 NULL,
 SYS_RES_ENERGY,
 (Vchar*)"DAMP",
 0,
 {SYS_QUA_NONE, SYS_QUA_NONE},
 3,
 0},
{(Vchar*)"Force", 1, -2, 0, 6, SYS_SIXDOF, 0, NULL, SYS_RES_EN_FORC, (Vchar*)"", 0, {SYS_QUA_NONE, SYS_QUA_NONE}, 3, 0},
{(Vchar*)"Strain_rate_tensor",
 2,
 0,
 0,
 6,
 SYS_TENSOR,
 0,
 NULL,
 SYS_RES_E_RATE,
 (Vchar*)"",
 0,
 {SYS_QUA_NONE, SYS_QUA_NONE},
 6,
 0},
{(Vchar*)"Translational_Velocity", 1, 0, 0, 6, SYS_SIXDOF, 0, NULL, SYS_RES_V, (Vchar*)"", 0, {SYS_QUA_NONE, SYS_QUA_NONE}, 3, 0},
{(Vchar*)"Principal_Stress2D",
 1,
 0,
 0,
 3,
 SYS_VECTOR,
 0,
 NULL,
 SYS_RES_S,
 (Vchar*)"",
 1,
 {SYS_QUA_PRINCIPAL, SYS_QUA_NONE},
 2,
 0},
{(Vchar*)"PSD_Acceleration_Local", 1, 0, 0, 6, SYS_SIXDOF, 0, NULL, SYS_RES_A, (Vchar*)"", 1, {SYS_QUA_PSD, SYS_QUA_NONE}, 3, 0},
{(Vchar*)"Torsion_Moment", 0, 3, 0, 8, SYS_ELEMRES, 3, NULL, SYS_RES_SFM, (Vchar*)"", 0, {SYS_QUA_NONE, SYS_QUA_NONE}, 1, 0},
{(Vchar*)"PSD_Displacement", 1, 0, 0, 6, SYS_SIXDOF, 0, NULL, SYS_RES_D, (Vchar*)"", 1, {SYS_QUA_PSD, SYS_QUA_NONE}, 3, 0},
{(Vchar*)"Reaction Force loc", 1, 0, 0, 6, SYS_SIXDOF, 0, NULL, SYS_RES_R, (Vchar*)"", 0, {SYS_QUA_NONE, SYS_QUA_NONE}, 6, 0},
{(Vchar*)"Total_Kinetic_Energy", 0, 0, 0, 1, SYS_SCALAR, 0, NULL, SYS_RES_KE, (Vchar*)"", 0, {SYS_QUA_NONE, SYS_QUA_NONE}, 3, 0},
{(Vchar*)"Equivalent_Plastic_Strain",
 0,
 0,
 0,
 1,
 SYS_SCALAR,
 0,
 NULL,
 SYS_RES_E,
 (Vchar*)"",
 2,
 {SYS_QUA_EQUIV, SYS_QUA_PLAST},
 1,
 0},
{(Vchar*)"Local_Strain_Tensor", 2, 0, 0, 6, SYS_TENSOR, 0, NULL, SYS_RES_E, (Vchar*)"", 0, {SYS_QUA_NONE, SYS_QUA_NONE}, 6, 0},
{(Vchar*)"Time", 0, 0, 0, 1, SYS_SCALAR, 0, NULL, SYS_RES_TIME, (Vchar*)"", 0, {SYS_QUA_NONE, SYS_QUA_NONE}, 1, 0},
{(Vchar*)"Max_Creep_Strain", 0, 0, 0, 1, SYS_SCALAR, 0, NULL, SYS_RES_E, (Vchar*)"", 2, {SYS_QUA_MAXIMUM, SYS_QUA_CREEP}, 1, 0},
{(Vchar*)"Principal_Strain", 1, 0, 0, 3, SYS_VECTOR, 0, NULL, SYS_RES_E, (Vchar*)"", 1, {SYS_QUA_PRINCIPAL, SYS_QUA_NONE}, 3, 0},
{(Vchar*)"Normal_Contact_Pressure",
 0,
 0,
 0,
 1,
 SYS_SCALAR,
 0,
 NULL,
 SYS_RES_PRES,
 (Vchar*)"",
 2,
 {SYS_QUA_CONTACT, SYS_QUA_NORMAL},
 1,
 0},
{(Vchar*)"PSD_Acceleration", 1, 0, 0, 6, SYS_SIXDOF, 0, NULL, SYS_RES_A, (Vchar*)"", 1, {SYS_QUA_PSD, SYS_QUA_NONE}, 3, 0},
{(Vchar*)"Maximum_Von_Mises_stress",
 0,
 0,
 0,
 1,
 SYS_SCALAR,
 0,
 NULL,
 SYS_RES_S,
 (Vchar*)"",
 2,
 {SYS_QUA_MAXIMUM, SYS_QUA_VONMISES},
 1,
 0},
{(Vchar*)"Minimum_Von_Mises_stress",
 0,
 0,
 0,
 1,
 SYS_SCALAR,
 0,
 NULL,
 SYS_RES_S,
 (Vchar*)"",
 2,
 {SYS_QUA_MINIMUM, SYS_QUA_VONMISES},
 1,
 0},
{(Vchar*)"PSD_Displacement_local", 1, 0, 0, 6, SYS_SIXDOF, 0, NULL, SYS_RES_D, (Vchar*)"", 1, {SYS_QUA_PSD, SYS_QUA_NONE}, 3, 0},
{(Vchar*)"Temperature", 0, 0, 0, 1, SYS_SCALAR, 0, NULL, SYS_RES_TEMP, (Vchar*)"", 0, {SYS_QUA_NONE, SYS_QUA_NONE}, 1, 0},
{(Vchar*)"Enthalpy", 0, 0, 0, 1, SYS_SCALAR, 0, NULL, SYS_RES_H, (Vchar*)"", 0, {SYS_QUA_NONE, SYS_QUA_NONE}, 1, 0},
{(Vchar*)"PSD_Velocity", 1, 0, 0, 6, SYS_SIXDOF, 0, NULL, SYS_RES_V, (Vchar*)"", 1, {SYS_QUA_PSD, SYS_QUA_NONE}, 3, 0},
{(Vchar*)"Equivalent_Stress3D_Corner",
 0,
 0,
 0,
 1,
 SYS_SCALAR,
 0,
 NULL,
 SYS_RES_S,
 (Vchar*)"",
 1,
 {SYS_QUA_EQUIV, SYS_QUA_NONE},
 1,
 0},
{(Vchar*)"Local_Stress_Tensor", 2, 0, 0, 6, SYS_TENSOR, 0, NULL, SYS_RES_S, (Vchar*)"", 0, {SYS_QUA_NONE, SYS_QUA_NONE}, 6, 0},
{(Vchar*)"SPH_Pressure", 0, 0, 0, 1, SYS_SCALAR, 0, NULL, SYS_RES_PRES, (Vchar*)"SPH", 0, {SYS_QUA_NONE, SYS_QUA_NONE}, 3, 0},
{(Vchar*)"Gauge_Pressure", 0, 0, 0, 1, SYS_SCALAR, 0, NULL, SYS_RES_PRES, (Vchar*)"GAUGE", 0, {SYS_QUA_NONE, SYS_QUA_NONE}, 3, 0},
{(Vchar*)"Contact_Pressure", 1, 0, 0, 3, SYS_VECTOR, 0, NULL, SYS_RES_PRES, (Vchar*)"", 1, {SYS_QUA_CONTACT, SYS_QUA_NONE}, 3, 0},
{(Vchar*)"COR_Velocity", 1, 0, 0, 6, SYS_SIXDOF, 0, NULL, SYS_RES_V, (Vchar*)"COR", 0, {SYS_QUA_NONE, SYS_QUA_NONE}, 3, 0},
{(Vchar*)"Normal_Force", 0, 0, 0, 1, SYS_SCALAR, 0, NULL, SYS_RES_FORCE, (Vchar*)"", 1, {SYS_QUA_NORMAL, SYS_QUA_NONE}, 2, 0},
{(Vchar*)"SPH_Density", 0, 0, 0, 1, SYS_SCALAR, 0, NULL, SYS_RES_DENS, (Vchar*)"SPH", 0, {SYS_QUA_NONE, SYS_QUA_NONE}, 3, 0},
{(Vchar*)"Internal_Energy_per_Element",
 0,
 0,
 0,
 1,
 SYS_SCALAR,
 0,
 NULL,
 SYS_RES_ENERGY,
 (Vchar*)"",
 1,
 {SYS_QUA_INTERNAL, SYS_QUA_NONE},
 1,
 0},
{(Vchar*)"Rotation_N1_S", 0, 1, 0, 8, SYS_ELEMRES, 1, NULL, SYS_RES_SEK, (Vchar*)"", 0, {SYS_QUA_NONE, SYS_QUA_NONE}, 2, 0},
{(Vchar*)"Rotation_N1_T", 0, 1, 0, 8, SYS_ELEMRES, 2, NULL, SYS_RES_SEK, (Vchar*)"", 0, {SYS_QUA_NONE, SYS_QUA_NONE}, 2, 0},
{(Vchar*)"Rotation_N2_S", 0, 2, 0, 8, SYS_ELEMRES, 1, NULL, SYS_RES_SEK, (Vchar*)"", 0, {SYS_QUA_NONE, SYS_QUA_NONE}, 2, 0},
{(Vchar*)"Rotation_N2_T", 0, 2, 0, 8, SYS_ELEMRES, 2, NULL, SYS_RES_SEK, (Vchar*)"", 0, {SYS_QUA_NONE, SYS_QUA_NONE}, 2, 0},
{(Vchar*)"Moment_N1", 1, 1, 0, 6, SYS_SIXDOF, 3, NULL, SYS_RES_EN_FORC, (Vchar*)"", 0, {SYS_QUA_NONE, SYS_QUA_NONE}, 3, 0},
{(Vchar*)"Moment_N2", 1, 2, 0, 6, SYS_SIXDOF, 3, NULL, SYS_RES_EN_FORC, (Vchar*)"", 0, {SYS_QUA_NONE, SYS_QUA_NONE}, 3, 0},
{(Vchar*)"Force_N1", 1, 1, 0, 6, SYS_SIXDOF, 0, NULL, SYS_RES_EN_FORC, (Vchar*)"", 0, {SYS_QUA_NONE, SYS_QUA_NONE}, 3, 0},
{(Vchar*)"Force_N2", 1, 2, 0, 6, SYS_SIXDOF, 0, NULL, SYS_RES_EN_FORC, (Vchar*)"", 0, {SYS_QUA_NONE, SYS_QUA_NONE}, 3, 0},
{NULL, 1, 0, 0, 1, SYS_SCALAR, 0, NULL, SYS_RES_UNKNOWN, (Vchar*)"", 0, {SYS_QUA_NONE, SYS_QUA_NONE}, 1, 0}};
#endif
